/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthLoginEndPost200Response,
  AuthLoginStartPost200Response,
  AuthRegisterPost400Response,
  AuthSessionGet200Response,
  LoginEndRequest,
  LoginStartRequest,
  ModelApiResponse,
  RefreshRequest,
  RegisterRequest,
  ValidationErrorResponse,
} from '../models/index';
import {
    AuthLoginEndPost200ResponseFromJSON,
    AuthLoginEndPost200ResponseToJSON,
    AuthLoginStartPost200ResponseFromJSON,
    AuthLoginStartPost200ResponseToJSON,
    AuthRegisterPost400ResponseFromJSON,
    AuthRegisterPost400ResponseToJSON,
    AuthSessionGet200ResponseFromJSON,
    AuthSessionGet200ResponseToJSON,
    LoginEndRequestFromJSON,
    LoginEndRequestToJSON,
    LoginStartRequestFromJSON,
    LoginStartRequestToJSON,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    RefreshRequestFromJSON,
    RefreshRequestToJSON,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface AuthLoginEndPostRequest {
    loginEndRequest: LoginEndRequest;
}

export interface AuthLoginStartPostRequest {
    loginStartRequest: LoginStartRequest;
}

export interface AuthRefreshPostRequest {
    refreshRequest: RefreshRequest;
}

export interface AuthRegisterPostRequest {
    registerRequest: RegisterRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Complete login process (verify OTP)
     */
    async authLoginEndPostRaw(requestParameters: AuthLoginEndPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginEndPost200Response>> {
        if (requestParameters['loginEndRequest'] == null) {
            throw new runtime.RequiredError(
                'loginEndRequest',
                'Required parameter "loginEndRequest" was null or undefined when calling authLoginEndPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login/end`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginEndRequestToJSON(requestParameters['loginEndRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginEndPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Complete login process (verify OTP)
     */
    async authLoginEndPost(requestParameters: AuthLoginEndPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginEndPost200Response> {
        const response = await this.authLoginEndPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start login process (request OTP)
     */
    async authLoginStartPostRaw(requestParameters: AuthLoginStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginStartPost200Response>> {
        if (requestParameters['loginStartRequest'] == null) {
            throw new runtime.RequiredError(
                'loginStartRequest',
                'Required parameter "loginStartRequest" was null or undefined when calling authLoginStartPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login/start`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginStartRequestToJSON(requestParameters['loginStartRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginStartPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Start login process (request OTP)
     */
    async authLoginStartPost(requestParameters: AuthLoginStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginStartPost200Response> {
        const response = await this.authLoginStartPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refresh access token
     */
    async authRefreshPostRaw(requestParameters: AuthRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginEndPost200Response>> {
        if (requestParameters['refreshRequest'] == null) {
            throw new runtime.RequiredError(
                'refreshRequest',
                'Required parameter "refreshRequest" was null or undefined when calling authRefreshPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/refresh`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshRequestToJSON(requestParameters['refreshRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginEndPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Refresh access token
     */
    async authRefreshPost(requestParameters: AuthRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginEndPost200Response> {
        const response = await this.authRefreshPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register a new user
     */
    async authRegisterPostRaw(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling authRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Register a new user
     */
    async authRegisterPost(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.authRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current user session
     */
    async authSessionGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthSessionGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/session`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthSessionGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get current user session
     */
    async authSessionGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthSessionGet200Response> {
        const response = await this.authSessionGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Health check
     */
    async healthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Health check
     */
    async healthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.healthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Home page
     */
    async rootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Home page
     */
    async rootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.rootGetRaw(initOverrides);
        return await response.value();
    }

}
