/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AiQueryPost200Response,
  AuthLoginEndPost200Response,
  AuthLoginStartPost200Response,
  AuthRegisterPost400Response,
  AuthSessionGet200Response,
  ClassesGet200Response,
  ClassesPost201Response,
  CreateClassRequest,
  FreeQueryRequest,
  LoginEndRequest,
  LoginStartRequest,
  ModelApiResponse,
  RefreshRequest,
  RegisterRequest,
  UpdateClassRequest,
  ValidationErrorResponse,
} from '../models/index';
import {
    AiQueryPost200ResponseFromJSON,
    AiQueryPost200ResponseToJSON,
    AuthLoginEndPost200ResponseFromJSON,
    AuthLoginEndPost200ResponseToJSON,
    AuthLoginStartPost200ResponseFromJSON,
    AuthLoginStartPost200ResponseToJSON,
    AuthRegisterPost400ResponseFromJSON,
    AuthRegisterPost400ResponseToJSON,
    AuthSessionGet200ResponseFromJSON,
    AuthSessionGet200ResponseToJSON,
    ClassesGet200ResponseFromJSON,
    ClassesGet200ResponseToJSON,
    ClassesPost201ResponseFromJSON,
    ClassesPost201ResponseToJSON,
    CreateClassRequestFromJSON,
    CreateClassRequestToJSON,
    FreeQueryRequestFromJSON,
    FreeQueryRequestToJSON,
    LoginEndRequestFromJSON,
    LoginEndRequestToJSON,
    LoginStartRequestFromJSON,
    LoginStartRequestToJSON,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    RefreshRequestFromJSON,
    RefreshRequestToJSON,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
    UpdateClassRequestFromJSON,
    UpdateClassRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface AiQueryPostRequest {
    freeQueryRequest: FreeQueryRequest;
}

export interface AuthLoginEndPostRequest {
    loginEndRequest: LoginEndRequest;
}

export interface AuthLoginStartPostRequest {
    loginStartRequest: LoginStartRequest;
}

export interface AuthRefreshPostRequest {
    refreshRequest: RefreshRequest;
}

export interface AuthRegisterPostRequest {
    registerRequest: RegisterRequest;
}

export interface ClassesIdDeleteRequest {
    id: number;
}

export interface ClassesIdGetRequest {
    id: number;
}

export interface ClassesIdPutRequest {
    id: number;
    updateClassRequest: UpdateClassRequest;
}

export interface ClassesPostRequest {
    createClassRequest: CreateClassRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Sends a free-form prompt to the Gemini model and returns the generated text response.
     * Free Gemini AI query
     */
    async aiQueryPostRaw(requestParameters: AiQueryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiQueryPost200Response>> {
        if (requestParameters['freeQueryRequest'] == null) {
            throw new runtime.RequiredError(
                'freeQueryRequest',
                'Required parameter "freeQueryRequest" was null or undefined when calling aiQueryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/ai/query`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FreeQueryRequestToJSON(requestParameters['freeQueryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiQueryPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Sends a free-form prompt to the Gemini model and returns the generated text response.
     * Free Gemini AI query
     */
    async aiQueryPost(requestParameters: AiQueryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiQueryPost200Response> {
        const response = await this.aiQueryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Complete login process (verify OTP)
     */
    async authLoginEndPostRaw(requestParameters: AuthLoginEndPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginEndPost200Response>> {
        if (requestParameters['loginEndRequest'] == null) {
            throw new runtime.RequiredError(
                'loginEndRequest',
                'Required parameter "loginEndRequest" was null or undefined when calling authLoginEndPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login/end`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginEndRequestToJSON(requestParameters['loginEndRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginEndPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Complete login process (verify OTP)
     */
    async authLoginEndPost(requestParameters: AuthLoginEndPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginEndPost200Response> {
        const response = await this.authLoginEndPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start login process (request OTP)
     */
    async authLoginStartPostRaw(requestParameters: AuthLoginStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginStartPost200Response>> {
        if (requestParameters['loginStartRequest'] == null) {
            throw new runtime.RequiredError(
                'loginStartRequest',
                'Required parameter "loginStartRequest" was null or undefined when calling authLoginStartPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login/start`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginStartRequestToJSON(requestParameters['loginStartRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginStartPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Start login process (request OTP)
     */
    async authLoginStartPost(requestParameters: AuthLoginStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginStartPost200Response> {
        const response = await this.authLoginStartPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refresh access token
     */
    async authRefreshPostRaw(requestParameters: AuthRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginEndPost200Response>> {
        if (requestParameters['refreshRequest'] == null) {
            throw new runtime.RequiredError(
                'refreshRequest',
                'Required parameter "refreshRequest" was null or undefined when calling authRefreshPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/refresh`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshRequestToJSON(requestParameters['refreshRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginEndPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Refresh access token
     */
    async authRefreshPost(requestParameters: AuthRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginEndPost200Response> {
        const response = await this.authRefreshPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register a new user
     */
    async authRegisterPostRaw(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling authRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Register a new user
     */
    async authRegisterPost(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.authRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current user session
     */
    async authSessionGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthSessionGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/session`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthSessionGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get current user session
     */
    async authSessionGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthSessionGet200Response> {
        const response = await this.authSessionGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns all school classes. Accessible by teachers and admins.
     * List all school classes
     */
    async classesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassesGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/classes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns all school classes. Accessible by teachers and admins.
     * List all school classes
     */
    async classesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassesGet200Response> {
        const response = await this.classesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Deletes a school class. Only accessible by admins.
     * Delete a school class
     */
    async classesIdDeleteRaw(requestParameters: ClassesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelApiResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling classesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/classes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelApiResponseFromJSON(jsonValue));
    }

    /**
     * Deletes a school class. Only accessible by admins.
     * Delete a school class
     */
    async classesIdDelete(requestParameters: ClassesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelApiResponse> {
        const response = await this.classesIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a single school class. Accessible by teachers and admins.
     * Get a school class by ID
     */
    async classesIdGetRaw(requestParameters: ClassesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassesPost201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling classesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/classes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassesPost201ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single school class. Accessible by teachers and admins.
     * Get a school class by ID
     */
    async classesIdGet(requestParameters: ClassesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassesPost201Response> {
        const response = await this.classesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a school class name. Teachers may only update classes they created. Admins may update any class. 
     * Update a school class
     */
    async classesIdPutRaw(requestParameters: ClassesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassesPost201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling classesIdPut().'
            );
        }

        if (requestParameters['updateClassRequest'] == null) {
            throw new runtime.RequiredError(
                'updateClassRequest',
                'Required parameter "updateClassRequest" was null or undefined when calling classesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/classes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateClassRequestToJSON(requestParameters['updateClassRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassesPost201ResponseFromJSON(jsonValue));
    }

    /**
     * Updates a school class name. Teachers may only update classes they created. Admins may update any class. 
     * Update a school class
     */
    async classesIdPut(requestParameters: ClassesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassesPost201Response> {
        const response = await this.classesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new school class. Accessible by teachers and admins.
     * Create a school class
     */
    async classesPostRaw(requestParameters: ClassesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassesPost201Response>> {
        if (requestParameters['createClassRequest'] == null) {
            throw new runtime.RequiredError(
                'createClassRequest',
                'Required parameter "createClassRequest" was null or undefined when calling classesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/classes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateClassRequestToJSON(requestParameters['createClassRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassesPost201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new school class. Accessible by teachers and admins.
     * Create a school class
     */
    async classesPost(requestParameters: ClassesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassesPost201Response> {
        const response = await this.classesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Health check
     */
    async healthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Health check
     */
    async healthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.healthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Home page
     */
    async rootGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Home page
     */
    async rootGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.rootGetRaw(initOverrides);
        return await response.value();
    }

}
