/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiConflictInfo
 */
export interface AiConflictInfo {
    /**
     * 
     * @type {string}
     * @memberof AiConflictInfo
     */
    code: AiConflictInfoCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof AiConflictInfo
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof AiConflictInfo
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof AiConflictInfo
     */
    groupId?: string;
    /**
     * 
     * @type {string}
     * @memberof AiConflictInfo
     */
    expectedRevision?: string;
    /**
     * 
     * @type {string}
     * @memberof AiConflictInfo
     */
    actualRevision?: string;
    /**
     * 
     * @type {string}
     * @memberof AiConflictInfo
     */
    hint?: string;
}


/**
 * @export
 */
export const AiConflictInfoCodeEnum = {
    StaleRevision: 'stale_revision',
    InvalidTarget: 'invalid_target',
    InvalidPayload: 'invalid_payload'
} as const;
export type AiConflictInfoCodeEnum = typeof AiConflictInfoCodeEnum[keyof typeof AiConflictInfoCodeEnum];


/**
 * Check if a given object implements the AiConflictInfo interface.
 */
export function instanceOfAiConflictInfo(value: object): value is AiConflictInfo {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AiConflictInfoFromJSON(json: any): AiConflictInfo {
    return AiConflictInfoFromJSONTyped(json, false);
}

export function AiConflictInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiConflictInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'operationId': json['operationId'] == null ? undefined : json['operationId'],
        'groupId': json['groupId'] == null ? undefined : json['groupId'],
        'expectedRevision': json['expectedRevision'] == null ? undefined : json['expectedRevision'],
        'actualRevision': json['actualRevision'] == null ? undefined : json['actualRevision'],
        'hint': json['hint'] == null ? undefined : json['hint'],
    };
}

export function AiConflictInfoToJSON(json: any): AiConflictInfo {
    return AiConflictInfoToJSONTyped(json, false);
}

export function AiConflictInfoToJSONTyped(value?: AiConflictInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'operationId': value['operationId'],
        'groupId': value['groupId'],
        'expectedRevision': value['expectedRevision'],
        'actualRevision': value['actualRevision'],
        'hint': value['hint'],
    };
}

