/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiDiffGroup
 */
export interface AiDiffGroup {
    /**
     * 
     * @type {string}
     * @memberof AiDiffGroup
     */
    groupId: string;
    /**
     * 
     * @type {number}
     * @memberof AiDiffGroup
     */
    groupIndex: number;
    /**
     * 
     * @type {string}
     * @memberof AiDiffGroup
     */
    label: string;
    /**
     * Page/sheet identifier; currently always default-page.
     * @type {string}
     * @memberof AiDiffGroup
     */
    pageId: string;
    /**
     * Number of grouped operations controlled by one accept/reject.
     * @type {number}
     * @memberof AiDiffGroup
     */
    operationCount: number;
}

/**
 * Check if a given object implements the AiDiffGroup interface.
 */
export function instanceOfAiDiffGroup(value: object): value is AiDiffGroup {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('groupIndex' in value) || value['groupIndex'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('pageId' in value) || value['pageId'] === undefined) return false;
    if (!('operationCount' in value) || value['operationCount'] === undefined) return false;
    return true;
}

export function AiDiffGroupFromJSON(json: any): AiDiffGroup {
    return AiDiffGroupFromJSONTyped(json, false);
}

export function AiDiffGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiDiffGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'groupIndex': json['groupIndex'],
        'label': json['label'],
        'pageId': json['pageId'],
        'operationCount': json['operationCount'],
    };
}

export function AiDiffGroupToJSON(json: any): AiDiffGroup {
    return AiDiffGroupToJSONTyped(json, false);
}

export function AiDiffGroupToJSONTyped(value?: AiDiffGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groupId': value['groupId'],
        'groupIndex': value['groupIndex'],
        'label': value['label'],
        'pageId': value['pageId'],
        'operationCount': value['operationCount'],
    };
}

