/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiDiffTarget
 */
export interface AiDiffTarget {
    /**
     * 
     * @type {string}
     * @memberof AiDiffTarget
     */
    targetNodeId?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof AiDiffTarget
     */
    path?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof AiDiffTarget
     */
    pathVersion: string;
    /**
     * 
     * @type {number}
     * @memberof AiDiffTarget
     */
    startOffset?: number;
    /**
     * 
     * @type {number}
     * @memberof AiDiffTarget
     */
    endOffset?: number;
    /**
     * 
     * @type {string}
     * @memberof AiDiffTarget
     */
    insertPosition?: AiDiffTargetInsertPositionEnum;
}


/**
 * @export
 */
export const AiDiffTargetInsertPositionEnum = {
    Before: 'before',
    After: 'after',
    Inside: 'inside'
} as const;
export type AiDiffTargetInsertPositionEnum = typeof AiDiffTargetInsertPositionEnum[keyof typeof AiDiffTargetInsertPositionEnum];


/**
 * Check if a given object implements the AiDiffTarget interface.
 */
export function instanceOfAiDiffTarget(value: object): value is AiDiffTarget {
    if (!('pathVersion' in value) || value['pathVersion'] === undefined) return false;
    return true;
}

export function AiDiffTargetFromJSON(json: any): AiDiffTarget {
    return AiDiffTargetFromJSONTyped(json, false);
}

export function AiDiffTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiDiffTarget {
    if (json == null) {
        return json;
    }
    return {
        
        'targetNodeId': json['targetNodeId'] == null ? undefined : json['targetNodeId'],
        'path': json['path'] == null ? undefined : json['path'],
        'pathVersion': json['pathVersion'],
        'startOffset': json['startOffset'] == null ? undefined : json['startOffset'],
        'endOffset': json['endOffset'] == null ? undefined : json['endOffset'],
        'insertPosition': json['insertPosition'] == null ? undefined : json['insertPosition'],
    };
}

export function AiDiffTargetToJSON(json: any): AiDiffTarget {
    return AiDiffTargetToJSONTyped(json, false);
}

export function AiDiffTargetToJSONTyped(value?: AiDiffTarget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetNodeId': value['targetNodeId'],
        'path': value['path'],
        'pathVersion': value['pathVersion'],
        'startOffset': value['startOffset'],
        'endOffset': value['endOffset'],
        'insertPosition': value['insertPosition'],
    };
}

