/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiDiffTarget } from './AiDiffTarget';
import {
    AiDiffTargetFromJSON,
    AiDiffTargetFromJSONTyped,
    AiDiffTargetToJSON,
    AiDiffTargetToJSONTyped,
} from './AiDiffTarget';

/**
 * 
 * @export
 * @interface AiDiffOperation
 */
export interface AiDiffOperation {
    /**
     * 
     * @type {string}
     * @memberof AiDiffOperation
     */
    operationId: string;
    /**
     * 
     * @type {string}
     * @memberof AiDiffOperation
     */
    changeSetId: string;
    /**
     * 
     * @type {string}
     * @memberof AiDiffOperation
     */
    groupId: string;
    /**
     * 
     * @type {number}
     * @memberof AiDiffOperation
     */
    groupIndex: number;
    /**
     * 
     * @type {number}
     * @memberof AiDiffOperation
     */
    opIndex: number;
    /**
     * 
     * @type {string}
     * @memberof AiDiffOperation
     */
    action: AiDiffOperationActionEnum;
    /**
     * 
     * @type {AiDiffTarget}
     * @memberof AiDiffOperation
     */
    target: AiDiffTarget;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof AiDiffOperation
     */
    oldContent?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof AiDiffOperation
     */
    newContent?: Array<{ [key: string]: any; }>;
}


/**
 * @export
 */
export const AiDiffOperationActionEnum = {
    Add: 'add',
    Remove: 'remove',
    Replace: 'replace'
} as const;
export type AiDiffOperationActionEnum = typeof AiDiffOperationActionEnum[keyof typeof AiDiffOperationActionEnum];


/**
 * Check if a given object implements the AiDiffOperation interface.
 */
export function instanceOfAiDiffOperation(value: object): value is AiDiffOperation {
    if (!('operationId' in value) || value['operationId'] === undefined) return false;
    if (!('changeSetId' in value) || value['changeSetId'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('groupIndex' in value) || value['groupIndex'] === undefined) return false;
    if (!('opIndex' in value) || value['opIndex'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function AiDiffOperationFromJSON(json: any): AiDiffOperation {
    return AiDiffOperationFromJSONTyped(json, false);
}

export function AiDiffOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiDiffOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'operationId': json['operationId'],
        'changeSetId': json['changeSetId'],
        'groupId': json['groupId'],
        'groupIndex': json['groupIndex'],
        'opIndex': json['opIndex'],
        'action': json['action'],
        'target': AiDiffTargetFromJSON(json['target']),
        'oldContent': json['oldContent'] == null ? undefined : json['oldContent'],
        'newContent': json['newContent'] == null ? undefined : json['newContent'],
    };
}

export function AiDiffOperationToJSON(json: any): AiDiffOperation {
    return AiDiffOperationToJSONTyped(json, false);
}

export function AiDiffOperationToJSONTyped(value?: AiDiffOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operationId': value['operationId'],
        'changeSetId': value['changeSetId'],
        'groupId': value['groupId'],
        'groupIndex': value['groupIndex'],
        'opIndex': value['opIndex'],
        'action': value['action'],
        'target': AiDiffTargetToJSON(value['target']),
        'oldContent': value['oldContent'],
        'newContent': value['newContent'],
    };
}

