/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiQueryPost200Response
 */
export interface AiQueryPost200Response {
    /**
     * 
     * @type {number}
     * @memberof AiQueryPost200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AiQueryPost200Response
     */
    message?: string;
    /**
     * Generated text from the AI model
     * @type {string}
     * @memberof AiQueryPost200Response
     */
    text?: string;
}

/**
 * Check if a given object implements the AiQueryPost200Response interface.
 */
export function instanceOfAiQueryPost200Response(value: object): value is AiQueryPost200Response {
    return true;
}

export function AiQueryPost200ResponseFromJSON(json: any): AiQueryPost200Response {
    return AiQueryPost200ResponseFromJSONTyped(json, false);
}

export function AiQueryPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiQueryPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function AiQueryPost200ResponseToJSON(json: any): AiQueryPost200Response {
    return AiQueryPost200ResponseToJSONTyped(json, false);
}

export function AiQueryPost200ResponseToJSONTyped(value?: AiQueryPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'text': value['text'],
    };
}

