/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginEndPost200Response
 */
export interface AuthLoginEndPost200Response {
    /**
     * 
     * @type {number}
     * @memberof AuthLoginEndPost200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginEndPost200Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginEndPost200Response
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginEndPost200Response
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the AuthLoginEndPost200Response interface.
 */
export function instanceOfAuthLoginEndPost200Response(value: object): value is AuthLoginEndPost200Response {
    return true;
}

export function AuthLoginEndPost200ResponseFromJSON(json: any): AuthLoginEndPost200Response {
    return AuthLoginEndPost200ResponseFromJSONTyped(json, false);
}

export function AuthLoginEndPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginEndPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function AuthLoginEndPost200ResponseToJSON(json: any): AuthLoginEndPost200Response {
    return AuthLoginEndPost200ResponseToJSONTyped(json, false);
}

export function AuthLoginEndPost200ResponseToJSONTyped(value?: AuthLoginEndPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

