/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface AuthSessionGet200Response
 */
export interface AuthSessionGet200Response {
    /**
     * 
     * @type {number}
     * @memberof AuthSessionGet200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthSessionGet200Response
     */
    message?: string;
    /**
     * 
     * @type {User}
     * @memberof AuthSessionGet200Response
     */
    user?: User;
}

/**
 * Check if a given object implements the AuthSessionGet200Response interface.
 */
export function instanceOfAuthSessionGet200Response(value: object): value is AuthSessionGet200Response {
    return true;
}

export function AuthSessionGet200ResponseFromJSON(json: any): AuthSessionGet200Response {
    return AuthSessionGet200ResponseFromJSONTyped(json, false);
}

export function AuthSessionGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSessionGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
    };
}

export function AuthSessionGet200ResponseToJSON(json: any): AuthSessionGet200Response {
    return AuthSessionGet200ResponseToJSONTyped(json, false);
}

export function AuthSessionGet200ResponseToJSONTyped(value?: AuthSessionGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'user': UserToJSON(value['user']),
    };
}

