/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ModelApiResponse } from './ModelApiResponse';
import {
    instanceOfModelApiResponse,
    ModelApiResponseFromJSON,
    ModelApiResponseFromJSONTyped,
    ModelApiResponseToJSON,
} from './ModelApiResponse';
import type { ValidationErrorResponse } from './ValidationErrorResponse';
import {
    instanceOfValidationErrorResponse,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseFromJSONTyped,
    ValidationErrorResponseToJSON,
} from './ValidationErrorResponse';

/**
 * @type AuthRegisterPost400Response
 * 
 * @export
 */
export type AuthRegisterPost400Response = ModelApiResponse | ValidationErrorResponse;

export function AuthRegisterPost400ResponseFromJSON(json: any): AuthRegisterPost400Response {
    return AuthRegisterPost400ResponseFromJSONTyped(json, false);
}

export function AuthRegisterPost400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterPost400Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfModelApiResponse(json)) {
        return ModelApiResponseFromJSONTyped(json, true);
    }
    if (instanceOfValidationErrorResponse(json)) {
        return ValidationErrorResponseFromJSONTyped(json, true);
    }
    return {} as any;
}

export function AuthRegisterPost400ResponseToJSON(json: any): any {
    return AuthRegisterPost400ResponseToJSONTyped(json, false);
}

export function AuthRegisterPost400ResponseToJSONTyped(value?: AuthRegisterPost400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfModelApiResponse(value)) {
        return ModelApiResponseToJSON(value as ModelApiResponse);
    }
    if (instanceOfValidationErrorResponse(value)) {
        return ValidationErrorResponseToJSON(value as ValidationErrorResponse);
    }
    return {};
}

