/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginStartPost200Response
 */
export interface AuthLoginStartPost200Response {
    /**
     * 
     * @type {number}
     * @memberof AuthLoginStartPost200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginStartPost200Response
     */
    message?: string;
    /**
     * Timestamp when OTP expires
     * @type {number}
     * @memberof AuthLoginStartPost200Response
     */
    expiry?: number;
}

/**
 * Check if a given object implements the AuthLoginStartPost200Response interface.
 */
export function instanceOfAuthLoginStartPost200Response(value: object): value is AuthLoginStartPost200Response {
    return true;
}

export function AuthLoginStartPost200ResponseFromJSON(json: any): AuthLoginStartPost200Response {
    return AuthLoginStartPost200ResponseFromJSONTyped(json, false);
}

export function AuthLoginStartPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginStartPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'expiry': json['expiry'] == null ? undefined : json['expiry'],
    };
}

export function AuthLoginStartPost200ResponseToJSON(json: any): AuthLoginStartPost200Response {
    return AuthLoginStartPost200ResponseToJSONTyped(json, false);
}

export function AuthLoginStartPost200ResponseToJSONTyped(value?: AuthLoginStartPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'expiry': value['expiry'],
    };
}

