/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Student } from './Student';
import {
    StudentFromJSON,
    StudentFromJSONTyped,
    StudentToJSON,
    StudentToJSONTyped,
} from './Student';

/**
 * 
 * @export
 * @interface ClassesIdStudentsPost201Response
 */
export interface ClassesIdStudentsPost201Response {
    /**
     * 
     * @type {number}
     * @memberof ClassesIdStudentsPost201Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassesIdStudentsPost201Response
     */
    message?: string;
    /**
     * 
     * @type {Student}
     * @memberof ClassesIdStudentsPost201Response
     */
    student?: Student;
}

/**
 * Check if a given object implements the ClassesIdStudentsPost201Response interface.
 */
export function instanceOfClassesIdStudentsPost201Response(value: object): value is ClassesIdStudentsPost201Response {
    return true;
}

export function ClassesIdStudentsPost201ResponseFromJSON(json: any): ClassesIdStudentsPost201Response {
    return ClassesIdStudentsPost201ResponseFromJSONTyped(json, false);
}

export function ClassesIdStudentsPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassesIdStudentsPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'student': json['student'] == null ? undefined : StudentFromJSON(json['student']),
    };
}

export function ClassesIdStudentsPost201ResponseToJSON(json: any): ClassesIdStudentsPost201Response {
    return ClassesIdStudentsPost201ResponseToJSONTyped(json, false);
}

export function ClassesIdStudentsPost201ResponseToJSONTyped(value?: ClassesIdStudentsPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'student': StudentToJSON(value['student']),
    };
}

