/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassesIdMembersPostRequest
 */
export interface ClassesIdMembersPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ClassesIdMembersPostRequest
     */
    userId: number;
}

/**
 * Check if a given object implements the ClassesIdMembersPostRequest interface.
 */
export function instanceOfClassesIdMembersPostRequest(value: object): value is ClassesIdMembersPostRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ClassesIdMembersPostRequestFromJSON(json: any): ClassesIdMembersPostRequest {
    return ClassesIdMembersPostRequestFromJSONTyped(json, false);
}

export function ClassesIdMembersPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassesIdMembersPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function ClassesIdMembersPostRequestToJSON(json: any): ClassesIdMembersPostRequest {
    return ClassesIdMembersPostRequestToJSONTyped(json, false);
}

export function ClassesIdMembersPostRequestToJSONTyped(value?: ClassesIdMembersPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

