/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Student } from './Student';
import {
    StudentFromJSON,
    StudentFromJSONTyped,
    StudentToJSON,
    StudentToJSONTyped,
} from './Student';

/**
 * 
 * @export
 * @interface ClassesIdStudentsGet200Response
 */
export interface ClassesIdStudentsGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ClassesIdStudentsGet200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassesIdStudentsGet200Response
     */
    message?: string;
    /**
     * 
     * @type {Array<Student>}
     * @memberof ClassesIdStudentsGet200Response
     */
    students?: Array<Student>;
}

/**
 * Check if a given object implements the ClassesIdStudentsGet200Response interface.
 */
export function instanceOfClassesIdStudentsGet200Response(value: object): value is ClassesIdStudentsGet200Response {
    return true;
}

export function ClassesIdStudentsGet200ResponseFromJSON(json: any): ClassesIdStudentsGet200Response {
    return ClassesIdStudentsGet200ResponseFromJSONTyped(json, false);
}

export function ClassesIdStudentsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassesIdStudentsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'students': json['students'] == null ? undefined : ((json['students'] as Array<any>).map(StudentFromJSON)),
    };
}

export function ClassesIdStudentsGet200ResponseToJSON(json: any): ClassesIdStudentsGet200Response {
    return ClassesIdStudentsGet200ResponseToJSONTyped(json, false);
}

export function ClassesIdStudentsGet200ResponseToJSONTyped(value?: ClassesIdStudentsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'students': value['students'] == null ? undefined : ((value['students'] as Array<any>).map(StudentToJSON)),
    };
}

