/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface ClassesIdMembersPost201Response
 */
export interface ClassesIdMembersPost201Response {
    /**
     * 
     * @type {number}
     * @memberof ClassesIdMembersPost201Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassesIdMembersPost201Response
     */
    message?: string;
    /**
     * 
     * @type {User}
     * @memberof ClassesIdMembersPost201Response
     */
    member?: User;
}

/**
 * Check if a given object implements the ClassesIdMembersPost201Response interface.
 */
export function instanceOfClassesIdMembersPost201Response(value: object): value is ClassesIdMembersPost201Response {
    return true;
}

export function ClassesIdMembersPost201ResponseFromJSON(json: any): ClassesIdMembersPost201Response {
    return ClassesIdMembersPost201ResponseFromJSONTyped(json, false);
}

export function ClassesIdMembersPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassesIdMembersPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'member': json['member'] == null ? undefined : UserFromJSON(json['member']),
    };
}

export function ClassesIdMembersPost201ResponseToJSON(json: any): ClassesIdMembersPost201Response {
    return ClassesIdMembersPost201ResponseToJSONTyped(json, false);
}

export function ClassesIdMembersPost201ResponseToJSONTyped(value?: ClassesIdMembersPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'member': UserToJSON(value['member']),
    };
}

