/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface ClassesIdMembersGet200Response
 */
export interface ClassesIdMembersGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ClassesIdMembersGet200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassesIdMembersGet200Response
     */
    message?: string;
    /**
     * 
     * @type {Array<User>}
     * @memberof ClassesIdMembersGet200Response
     */
    members?: Array<User>;
}

/**
 * Check if a given object implements the ClassesIdMembersGet200Response interface.
 */
export function instanceOfClassesIdMembersGet200Response(value: object): value is ClassesIdMembersGet200Response {
    return true;
}

export function ClassesIdMembersGet200ResponseFromJSON(json: any): ClassesIdMembersGet200Response {
    return ClassesIdMembersGet200ResponseFromJSONTyped(json, false);
}

export function ClassesIdMembersGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassesIdMembersGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(UserFromJSON)),
    };
}

export function ClassesIdMembersGet200ResponseToJSON(json: any): ClassesIdMembersGet200Response {
    return ClassesIdMembersGet200ResponseToJSONTyped(json, false);
}

export function ClassesIdMembersGet200ResponseToJSONTyped(value?: ClassesIdMembersGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(UserToJSON)),
    };
}

