/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSubjectRequest
 */
export interface CreateSubjectRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSubjectRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateSubjectRequest interface.
 */
export function instanceOfCreateSubjectRequest(value: object): value is CreateSubjectRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateSubjectRequestFromJSON(json: any): CreateSubjectRequest {
    return CreateSubjectRequestFromJSONTyped(json, false);
}

export function CreateSubjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateSubjectRequestToJSON(json: any): CreateSubjectRequest {
    return CreateSubjectRequestToJSONTyped(json, false);
}

export function CreateSubjectRequestToJSONTyped(value?: CreateSubjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

