/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStudentRequest
 */
export interface CreateStudentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the CreateStudentRequest interface.
 */
export function instanceOfCreateStudentRequest(value: object): value is CreateStudentRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function CreateStudentRequestFromJSON(json: any): CreateStudentRequest {
    return CreateStudentRequestFromJSONTyped(json, false);
}

export function CreateStudentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStudentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function CreateStudentRequestToJSON(json: any): CreateStudentRequest {
    return CreateStudentRequestToJSONTyped(json, false);
}

export function CreateStudentRequestToJSONTyped(value?: CreateStudentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
    };
}

