/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDraftRequest
 */
export interface CreateDraftRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDraftRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDraftRequest
     */
    format: CreateDraftRequestFormatEnum;
    /**
     * 
     * @type {object}
     * @memberof CreateDraftRequest
     */
    content: object;
}


/**
 * @export
 */
export const CreateDraftRequestFormatEnum = {
    SimaVazlat: 'sima_vazlat',
    Oravazlat: 'oravazlat',
    EvesTanterv: 'eves_tanterv',
    Egyeb: 'egyeb'
} as const;
export type CreateDraftRequestFormatEnum = typeof CreateDraftRequestFormatEnum[keyof typeof CreateDraftRequestFormatEnum];


/**
 * Check if a given object implements the CreateDraftRequest interface.
 */
export function instanceOfCreateDraftRequest(value: object): value is CreateDraftRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateDraftRequestFromJSON(json: any): CreateDraftRequest {
    return CreateDraftRequestFromJSONTyped(json, false);
}

export function CreateDraftRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDraftRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'format': json['format'],
        'content': json['content'],
    };
}

export function CreateDraftRequestToJSON(json: any): CreateDraftRequest {
    return CreateDraftRequestToJSONTyped(json, false);
}

export function CreateDraftRequestToJSONTyped(value?: CreateDraftRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'format': value['format'],
        'content': value['content'],
    };
}

