/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiConflictInfo } from './AiConflictInfo';
import {
    AiConflictInfoFromJSON,
    AiConflictInfoFromJSONTyped,
    AiConflictInfoToJSON,
    AiConflictInfoToJSONTyped,
} from './AiConflictInfo';
import type { AiDiffGroup } from './AiDiffGroup';
import {
    AiDiffGroupFromJSON,
    AiDiffGroupFromJSONTyped,
    AiDiffGroupToJSON,
    AiDiffGroupToJSONTyped,
} from './AiDiffGroup';
import type { AiDiffOperation } from './AiDiffOperation';
import {
    AiDiffOperationFromJSON,
    AiDiffOperationFromJSONTyped,
    AiDiffOperationToJSON,
    AiDiffOperationToJSONTyped,
} from './AiDiffOperation';

/**
 * 
 * @export
 * @interface DraftAiEditResponse
 */
export interface DraftAiEditResponse {
    /**
     * 
     * @type {string}
     * @memberof DraftAiEditResponse
     */
    changeSetId: string;
    /**
     * 
     * @type {string}
     * @memberof DraftAiEditResponse
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftAiEditResponse
     */
    baseRevision: string;
    /**
     * 
     * @type {string}
     * @memberof DraftAiEditResponse
     */
    resultRevision: string;
    /**
     * 
     * @type {Array<AiDiffGroup>}
     * @memberof DraftAiEditResponse
     */
    groups: Array<AiDiffGroup>;
    /**
     * 
     * @type {Array<AiDiffOperation>}
     * @memberof DraftAiEditResponse
     */
    operations: Array<AiDiffOperation>;
    /**
     * 
     * @type {Array<AiConflictInfo>}
     * @memberof DraftAiEditResponse
     */
    conflicts: Array<AiConflictInfo>;
    /**
     * 
     * @type {string}
     * @memberof DraftAiEditResponse
     */
    checksum: string;
    /**
     * 
     * @type {string}
     * @memberof DraftAiEditResponse
     */
    messageToClient: string;
}

/**
 * Check if a given object implements the DraftAiEditResponse interface.
 */
export function instanceOfDraftAiEditResponse(value: object): value is DraftAiEditResponse {
    if (!('changeSetId' in value) || value['changeSetId'] === undefined) return false;
    if (!('baseRevision' in value) || value['baseRevision'] === undefined) return false;
    if (!('resultRevision' in value) || value['resultRevision'] === undefined) return false;
    if (!('groups' in value) || value['groups'] === undefined) return false;
    if (!('operations' in value) || value['operations'] === undefined) return false;
    if (!('conflicts' in value) || value['conflicts'] === undefined) return false;
    if (!('checksum' in value) || value['checksum'] === undefined) return false;
    if (!('messageToClient' in value) || value['messageToClient'] === undefined) return false;
    return true;
}

export function DraftAiEditResponseFromJSON(json: any): DraftAiEditResponse {
    return DraftAiEditResponseFromJSONTyped(json, false);
}

export function DraftAiEditResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftAiEditResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'changeSetId': json['changeSetId'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'baseRevision': json['baseRevision'],
        'resultRevision': json['resultRevision'],
        'groups': ((json['groups'] as Array<any>).map(AiDiffGroupFromJSON)),
        'operations': ((json['operations'] as Array<any>).map(AiDiffOperationFromJSON)),
        'conflicts': ((json['conflicts'] as Array<any>).map(AiConflictInfoFromJSON)),
        'checksum': json['checksum'],
        'messageToClient': json['messageToClient'],
    };
}

export function DraftAiEditResponseToJSON(json: any): DraftAiEditResponse {
    return DraftAiEditResponseToJSONTyped(json, false);
}

export function DraftAiEditResponseToJSONTyped(value?: DraftAiEditResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changeSetId': value['changeSetId'],
        'requestId': value['requestId'],
        'baseRevision': value['baseRevision'],
        'resultRevision': value['resultRevision'],
        'groups': ((value['groups'] as Array<any>).map(AiDiffGroupToJSON)),
        'operations': ((value['operations'] as Array<any>).map(AiDiffOperationToJSON)),
        'conflicts': ((value['conflicts'] as Array<any>).map(AiConflictInfoToJSON)),
        'checksum': value['checksum'],
        'messageToClient': value['messageToClient'],
    };
}

