/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DraftLinkIdPostRequest
 */
export interface DraftLinkIdPostRequest {
    /**
     * 
     * @type {number}
     * @memberof DraftLinkIdPostRequest
     */
    fileId?: number;
}

/**
 * Check if a given object implements the DraftLinkIdPostRequest interface.
 */
export function instanceOfDraftLinkIdPostRequest(value: object): value is DraftLinkIdPostRequest {
    return true;
}

export function DraftLinkIdPostRequestFromJSON(json: any): DraftLinkIdPostRequest {
    return DraftLinkIdPostRequestFromJSONTyped(json, false);
}

export function DraftLinkIdPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftLinkIdPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['fileId'] == null ? undefined : json['fileId'],
    };
}

export function DraftLinkIdPostRequestToJSON(json: any): DraftLinkIdPostRequest {
    return DraftLinkIdPostRequestToJSONTyped(json, false);
}

export function DraftLinkIdPostRequestToJSONTyped(value?: DraftLinkIdPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileId': value['fileId'],
    };
}

