/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DraftChatRequestCurrentContext } from './DraftChatRequestCurrentContext';
import {
    DraftChatRequestCurrentContextFromJSON,
    DraftChatRequestCurrentContextFromJSONTyped,
    DraftChatRequestCurrentContextToJSON,
    DraftChatRequestCurrentContextToJSONTyped,
} from './DraftChatRequestCurrentContext';
import type { DraftChatRequestBaseRevision } from './DraftChatRequestBaseRevision';
import {
    DraftChatRequestBaseRevisionFromJSON,
    DraftChatRequestBaseRevisionFromJSONTyped,
    DraftChatRequestBaseRevisionToJSON,
    DraftChatRequestBaseRevisionToJSONTyped,
} from './DraftChatRequestBaseRevision';

/**
 * 
 * @export
 * @interface DraftChatRequest
 */
export interface DraftChatRequest {
    /**
     * 
     * @type {string}
     * @memberof DraftChatRequest
     */
    message: string;
    /**
     * 
     * @type {DraftChatRequestCurrentContext}
     * @memberof DraftChatRequest
     */
    currentContext?: DraftChatRequestCurrentContext;
    /**
     * Optional allowed Slate elements or editor constraints.
     * @type {Array<string>}
     * @memberof DraftChatRequest
     */
    editorOptions?: Array<string>;
    /**
     * 
     * @type {DraftChatRequestBaseRevision}
     * @memberof DraftChatRequest
     */
    baseRevision?: DraftChatRequestBaseRevision;
    /**
     * Optional request-level mode override. Defaults to grouped.
     * @type {string}
     * @memberof DraftChatRequest
     */
    responseMode?: DraftChatRequestResponseModeEnum;
    /**
     * Optional correlation id echoed by the server.
     * @type {string}
     * @memberof DraftChatRequest
     */
    requestId?: string;
    /**
     * Optional replay key for deterministic change set generation.
     * @type {string}
     * @memberof DraftChatRequest
     */
    idempotencyKey?: string;
}


/**
 * @export
 */
export const DraftChatRequestResponseModeEnum = {
    Legacy: 'legacy',
    Grouped: 'grouped',
    Dual: 'dual'
} as const;
export type DraftChatRequestResponseModeEnum = typeof DraftChatRequestResponseModeEnum[keyof typeof DraftChatRequestResponseModeEnum];


/**
 * Check if a given object implements the DraftChatRequest interface.
 */
export function instanceOfDraftChatRequest(value: object): value is DraftChatRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DraftChatRequestFromJSON(json: any): DraftChatRequest {
    return DraftChatRequestFromJSONTyped(json, false);
}

export function DraftChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'currentContext': json['currentContext'] == null ? undefined : DraftChatRequestCurrentContextFromJSON(json['currentContext']),
        'editorOptions': json['editorOptions'] == null ? undefined : json['editorOptions'],
        'baseRevision': json['baseRevision'] == null ? undefined : DraftChatRequestBaseRevisionFromJSON(json['baseRevision']),
        'responseMode': json['responseMode'] == null ? undefined : json['responseMode'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'idempotencyKey': json['idempotencyKey'] == null ? undefined : json['idempotencyKey'],
    };
}

export function DraftChatRequestToJSON(json: any): DraftChatRequest {
    return DraftChatRequestToJSONTyped(json, false);
}

export function DraftChatRequestToJSONTyped(value?: DraftChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'currentContext': DraftChatRequestCurrentContextToJSON(value['currentContext']),
        'editorOptions': value['editorOptions'],
        'baseRevision': DraftChatRequestBaseRevisionToJSON(value['baseRevision']),
        'responseMode': value['responseMode'],
        'requestId': value['requestId'],
        'idempotencyKey': value['idempotencyKey'],
    };
}

