/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DraftLinkedFile
 */
export interface DraftLinkedFile {
    /**
     * 
     * @type {number}
     * @memberof DraftLinkedFile
     */
    fileId: number;
    /**
     * 
     * @type {string}
     * @memberof DraftLinkedFile
     */
    filename: string;
    /**
     * 
     * @type {number}
     * @memberof DraftLinkedFile
     */
    sizeBytes?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DraftLinkedFile
     */
    mimeType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DraftLinkedFile
     */
    contextStatus?: DraftLinkedFileContextStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof DraftLinkedFile
     */
    contextMode?: DraftLinkedFileContextModeEnum;
    /**
     * 
     * @type {string}
     * @memberof DraftLinkedFile
     */
    statusMessage?: string;
}


/**
 * @export
 */
export const DraftLinkedFileContextStatusEnum = {
    Ready: 'ready',
    Processing: 'processing',
    Fallback: 'fallback',
    Blocked: 'blocked',
    Error: 'error'
} as const;
export type DraftLinkedFileContextStatusEnum = typeof DraftLinkedFileContextStatusEnum[keyof typeof DraftLinkedFileContextStatusEnum];

/**
 * @export
 */
export const DraftLinkedFileContextModeEnum = {
    GeminiFile: 'gemini_file',
    FallbackText: 'fallback_text',
    None: 'none'
} as const;
export type DraftLinkedFileContextModeEnum = typeof DraftLinkedFileContextModeEnum[keyof typeof DraftLinkedFileContextModeEnum];


/**
 * Check if a given object implements the DraftLinkedFile interface.
 */
export function instanceOfDraftLinkedFile(value: object): value is DraftLinkedFile {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    return true;
}

export function DraftLinkedFileFromJSON(json: any): DraftLinkedFile {
    return DraftLinkedFileFromJSONTyped(json, false);
}

export function DraftLinkedFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftLinkedFile {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['fileId'],
        'filename': json['filename'],
        'sizeBytes': json['sizeBytes'] == null ? undefined : json['sizeBytes'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'contextStatus': json['contextStatus'] == null ? undefined : json['contextStatus'],
        'contextMode': json['contextMode'] == null ? undefined : json['contextMode'],
        'statusMessage': json['statusMessage'] == null ? undefined : json['statusMessage'],
    };
}

export function DraftLinkedFileToJSON(json: any): DraftLinkedFile {
    return DraftLinkedFileToJSONTyped(json, false);
}

export function DraftLinkedFileToJSONTyped(value?: DraftLinkedFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileId': value['fileId'],
        'filename': value['filename'],
        'sizeBytes': value['sizeBytes'],
        'mimeType': value['mimeType'],
        'contextStatus': value['contextStatus'],
        'contextMode': value['contextMode'],
        'statusMessage': value['statusMessage'],
    };
}

