/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LegacyAiOperation } from './LegacyAiOperation';
import {
    LegacyAiOperationFromJSON,
    LegacyAiOperationFromJSONTyped,
    LegacyAiOperationToJSON,
    LegacyAiOperationToJSONTyped,
} from './LegacyAiOperation';

/**
 * 
 * @export
 * @interface DraftAiLegacyResponse
 */
export interface DraftAiLegacyResponse {
    /**
     * 
     * @type {string}
     * @memberof DraftAiLegacyResponse
     */
    messageToClient: string;
    /**
     * 
     * @type {Array<LegacyAiOperation>}
     * @memberof DraftAiLegacyResponse
     */
    operations: Array<LegacyAiOperation>;
}

/**
 * Check if a given object implements the DraftAiLegacyResponse interface.
 */
export function instanceOfDraftAiLegacyResponse(value: object): value is DraftAiLegacyResponse {
    if (!('messageToClient' in value) || value['messageToClient'] === undefined) return false;
    if (!('operations' in value) || value['operations'] === undefined) return false;
    return true;
}

export function DraftAiLegacyResponseFromJSON(json: any): DraftAiLegacyResponse {
    return DraftAiLegacyResponseFromJSONTyped(json, false);
}

export function DraftAiLegacyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftAiLegacyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'messageToClient': json['messageToClient'],
        'operations': ((json['operations'] as Array<any>).map(LegacyAiOperationFromJSON)),
    };
}

export function DraftAiLegacyResponseToJSON(json: any): DraftAiLegacyResponse {
    return DraftAiLegacyResponseToJSONTyped(json, false);
}

export function DraftAiLegacyResponseToJSONTyped(value?: DraftAiLegacyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageToClient': value['messageToClient'],
        'operations': ((value['operations'] as Array<any>).map(LegacyAiOperationToJSON)),
    };
}

