/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DraftLinkedFile } from './DraftLinkedFile';
import {
    DraftLinkedFileFromJSON,
    DraftLinkedFileFromJSONTyped,
    DraftLinkedFileToJSON,
    DraftLinkedFileToJSONTyped,
} from './DraftLinkedFile';

/**
 * 
 * @export
 * @interface DraftsIdGet200Response
 */
export interface DraftsIdGet200Response {
    /**
     * 
     * @type {number}
     * @memberof DraftsIdGet200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof DraftsIdGet200Response
     */
    message?: string;
    /**
     * 
     * @type {object}
     * @memberof DraftsIdGet200Response
     */
    draft?: object;
    /**
     * 
     * @type {Array<DraftLinkedFile>}
     * @memberof DraftsIdGet200Response
     */
    files?: Array<DraftLinkedFile>;
}

/**
 * Check if a given object implements the DraftsIdGet200Response interface.
 */
export function instanceOfDraftsIdGet200Response(value: object): value is DraftsIdGet200Response {
    return true;
}

export function DraftsIdGet200ResponseFromJSON(json: any): DraftsIdGet200Response {
    return DraftsIdGet200ResponseFromJSONTyped(json, false);
}

export function DraftsIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftsIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'draft': json['draft'] == null ? undefined : json['draft'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(DraftLinkedFileFromJSON)),
    };
}

export function DraftsIdGet200ResponseToJSON(json: any): DraftsIdGet200Response {
    return DraftsIdGet200ResponseToJSONTyped(json, false);
}

export function DraftsIdGet200ResponseToJSONTyped(value?: DraftsIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'draft': value['draft'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(DraftLinkedFileToJSON)),
    };
}

