/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DraftAiEditDualResponse } from './DraftAiEditDualResponse';
import {
    instanceOfDraftAiEditDualResponse,
    DraftAiEditDualResponseFromJSON,
    DraftAiEditDualResponseFromJSONTyped,
    DraftAiEditDualResponseToJSON,
} from './DraftAiEditDualResponse';
import type { DraftAiEditResponse } from './DraftAiEditResponse';
import {
    instanceOfDraftAiEditResponse,
    DraftAiEditResponseFromJSON,
    DraftAiEditResponseFromJSONTyped,
    DraftAiEditResponseToJSON,
} from './DraftAiEditResponse';
import type { DraftAiLegacyResponse } from './DraftAiLegacyResponse';
import {
    instanceOfDraftAiLegacyResponse,
    DraftAiLegacyResponseFromJSON,
    DraftAiLegacyResponseFromJSONTyped,
    DraftAiLegacyResponseToJSON,
} from './DraftAiLegacyResponse';

/**
 * @type DraftChatsIdPost200ResponseAllOfResponse
 * 
 * @export
 */
export type DraftChatsIdPost200ResponseAllOfResponse = DraftAiEditDualResponse | DraftAiEditResponse | DraftAiLegacyResponse;

export function DraftChatsIdPost200ResponseAllOfResponseFromJSON(json: any): DraftChatsIdPost200ResponseAllOfResponse {
    return DraftChatsIdPost200ResponseAllOfResponseFromJSONTyped(json, false);
}

export function DraftChatsIdPost200ResponseAllOfResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftChatsIdPost200ResponseAllOfResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDraftAiEditDualResponse(json)) {
        return DraftAiEditDualResponseFromJSONTyped(json, true);
    }
    if (instanceOfDraftAiEditResponse(json)) {
        return DraftAiEditResponseFromJSONTyped(json, true);
    }
    if (instanceOfDraftAiLegacyResponse(json)) {
        return DraftAiLegacyResponseFromJSONTyped(json, true);
    }
    return {} as any;
}

export function DraftChatsIdPost200ResponseAllOfResponseToJSON(json: any): any {
    return DraftChatsIdPost200ResponseAllOfResponseToJSONTyped(json, false);
}

export function DraftChatsIdPost200ResponseAllOfResponseToJSONTyped(value?: DraftChatsIdPost200ResponseAllOfResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDraftAiEditDualResponse(value)) {
        return DraftAiEditDualResponseToJSON(value as DraftAiEditDualResponse);
    }
    if (instanceOfDraftAiEditResponse(value)) {
        return DraftAiEditResponseToJSON(value as DraftAiEditResponse);
    }
    if (instanceOfDraftAiLegacyResponse(value)) {
        return DraftAiLegacyResponseToJSON(value as DraftAiLegacyResponse);
    }
    return {};
}

