/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DraftChatsIdPost200ResponseAllOfResponse } from './DraftChatsIdPost200ResponseAllOfResponse';
import {
    DraftChatsIdPost200ResponseAllOfResponseFromJSON,
    DraftChatsIdPost200ResponseAllOfResponseFromJSONTyped,
    DraftChatsIdPost200ResponseAllOfResponseToJSON,
    DraftChatsIdPost200ResponseAllOfResponseToJSONTyped,
} from './DraftChatsIdPost200ResponseAllOfResponse';

/**
 * 
 * @export
 * @interface DraftChatsIdPost200Response
 */
export interface DraftChatsIdPost200Response {
    /**
     * 
     * @type {number}
     * @memberof DraftChatsIdPost200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof DraftChatsIdPost200Response
     */
    message?: string;
    /**
     * 
     * @type {DraftChatsIdPost200ResponseAllOfResponse}
     * @memberof DraftChatsIdPost200Response
     */
    response?: DraftChatsIdPost200ResponseAllOfResponse;
}

/**
 * Check if a given object implements the DraftChatsIdPost200Response interface.
 */
export function instanceOfDraftChatsIdPost200Response(value: object): value is DraftChatsIdPost200Response {
    return true;
}

export function DraftChatsIdPost200ResponseFromJSON(json: any): DraftChatsIdPost200Response {
    return DraftChatsIdPost200ResponseFromJSONTyped(json, false);
}

export function DraftChatsIdPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftChatsIdPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'response': json['response'] == null ? undefined : DraftChatsIdPost200ResponseAllOfResponseFromJSON(json['response']),
    };
}

export function DraftChatsIdPost200ResponseToJSON(json: any): DraftChatsIdPost200Response {
    return DraftChatsIdPost200ResponseToJSONTyped(json, false);
}

export function DraftChatsIdPost200ResponseToJSONTyped(value?: DraftChatsIdPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'response': DraftChatsIdPost200ResponseAllOfResponseToJSON(value['response']),
    };
}

