/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DraftChatsIdPostRequest
 */
export interface DraftChatsIdPostRequest {
  /**
   *
   * @type {string}
   * @memberof DraftChatsIdPostRequest
   */
  message?: string;
  /**
   * The current stringified plain text context of the frontend editor to use instead of the database draft content.
   * @type {any}
   * @memberof DraftChatsIdPostRequest
   */
  currentContext?: any;
  /**
   * Optional array of allowed Slate elements (e.g. ['paragraph', 'heading-one']) or structures the AI should follow.
   * @type {Array<string>}
   * @memberof DraftChatsIdPostRequest
   */
  editorOptions?: Array<string>;
  /**
   * Response contract mode during rollout.
   * @type {string}
   * @memberof DraftChatsIdPostRequest
   */
  responseMode?: "legacy" | "grouped" | "dual";
  /**
   * Client base revision for safety checks.
   * @type {string}
   * @memberof DraftChatsIdPostRequest
   */
  baseRevision?: string;
  /**
   * Client request id for tracing.
   * @type {string}
   * @memberof DraftChatsIdPostRequest
   */
  requestId?: string;
  /**
   * Idempotency key for retries.
   * @type {string}
   * @memberof DraftChatsIdPostRequest
   */
  idempotencyKey?: string;
}

/**
 * Check if a given object implements the DraftChatsIdPostRequest interface.
 */
export function instanceOfDraftChatsIdPostRequest(
  value: object,
): value is DraftChatsIdPostRequest {
  return true;
}

export function DraftChatsIdPostRequestFromJSON(
  json: any,
): DraftChatsIdPostRequest {
  return DraftChatsIdPostRequestFromJSONTyped(json, false);
}

export function DraftChatsIdPostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DraftChatsIdPostRequest {
  if (json == null) {
    return json;
  }
  return {
    message: json["message"] == null ? undefined : json["message"],
    currentContext:
      json["currentContext"] == null ? undefined : json["currentContext"],
    editorOptions:
      json["editorOptions"] == null ? undefined : json["editorOptions"],
    responseMode:
      json["responseMode"] == null ? undefined : json["responseMode"],
    baseRevision:
      json["baseRevision"] == null ? undefined : json["baseRevision"],
    requestId: json["requestId"] == null ? undefined : json["requestId"],
    idempotencyKey:
      json["idempotencyKey"] == null ? undefined : json["idempotencyKey"],
  };
}

export function DraftChatsIdPostRequestToJSON(
  json: any,
): DraftChatsIdPostRequest {
  return DraftChatsIdPostRequestToJSONTyped(json, false);
}

export function DraftChatsIdPostRequestToJSONTyped(
  value?: DraftChatsIdPostRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value["message"],
    currentContext: value["currentContext"],
    editorOptions: value["editorOptions"],
    responseMode: value["responseMode"],
    baseRevision: value["baseRevision"],
    requestId: value["requestId"],
    idempotencyKey: value["idempotencyKey"],
  };
}
