/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type DraftChatRequestCurrentContext
 * Current editor Slate JSON (array, node, or page envelope). String is accepted only for JSON-serialized content.
 * @export
 */
export type DraftChatRequestCurrentContext = Array<{ [key: string]: any; }> | string | { [key: string]: any; };

export function DraftChatRequestCurrentContextFromJSON(json: any): DraftChatRequestCurrentContext {
    return DraftChatRequestCurrentContextFromJSONTyped(json, false);
}

export function DraftChatRequestCurrentContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftChatRequestCurrentContext {
    if (json == null) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function DraftChatRequestCurrentContextToJSON(json: any): any {
    return DraftChatRequestCurrentContextToJSONTyped(json, false);
}

export function DraftChatRequestCurrentContextToJSONTyped(value?: DraftChatRequestCurrentContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

