/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamsIdAttachDraftPost200Response
 */
export interface ExamsIdAttachDraftPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ExamsIdAttachDraftPost200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ExamsIdAttachDraftPost200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ExamsIdAttachDraftPost200Response
     */
    fileId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExamsIdAttachDraftPost200Response
     */
    filename?: string;
    /**
     * 
     * @type {number}
     * @memberof ExamsIdAttachDraftPost200Response
     */
    draftId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExamsIdAttachDraftPost200Response
     */
    draftTitle?: string;
    /**
     * 
     * @type {Date}
     * @memberof ExamsIdAttachDraftPost200Response
     */
    draftUpdatedAt?: Date;
}

/**
 * Check if a given object implements the ExamsIdAttachDraftPost200Response interface.
 */
export function instanceOfExamsIdAttachDraftPost200Response(value: object): value is ExamsIdAttachDraftPost200Response {
    return true;
}

export function ExamsIdAttachDraftPost200ResponseFromJSON(json: any): ExamsIdAttachDraftPost200Response {
    return ExamsIdAttachDraftPost200ResponseFromJSONTyped(json, false);
}

export function ExamsIdAttachDraftPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamsIdAttachDraftPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'fileId': json['fileId'] == null ? undefined : json['fileId'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'draftId': json['draftId'] == null ? undefined : json['draftId'],
        'draftTitle': json['draftTitle'] == null ? undefined : json['draftTitle'],
        'draftUpdatedAt': json['draftUpdatedAt'] == null ? undefined : (new Date(json['draftUpdatedAt'])),
    };
}

export function ExamsIdAttachDraftPost200ResponseToJSON(json: any): ExamsIdAttachDraftPost200Response {
    return ExamsIdAttachDraftPost200ResponseToJSONTyped(json, false);
}

export function ExamsIdAttachDraftPost200ResponseToJSONTyped(value?: ExamsIdAttachDraftPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'fileId': value['fileId'],
        'filename': value['filename'],
        'draftId': value['draftId'],
        'draftTitle': value['draftTitle'],
        'draftUpdatedAt': value['draftUpdatedAt'] == null ? value['draftUpdatedAt'] : value['draftUpdatedAt'].toISOString(),
    };
}

