/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamAiEditRequestBaseRevision } from './ExamAiEditRequestBaseRevision';
import {
    ExamAiEditRequestBaseRevisionFromJSON,
    ExamAiEditRequestBaseRevisionFromJSONTyped,
    ExamAiEditRequestBaseRevisionToJSON,
    ExamAiEditRequestBaseRevisionToJSONTyped,
} from './ExamAiEditRequestBaseRevision';
import type { ExamClientQuestionRef } from './ExamClientQuestionRef';
import {
    ExamClientQuestionRefFromJSON,
    ExamClientQuestionRefFromJSONTyped,
    ExamClientQuestionRefToJSON,
    ExamClientQuestionRefToJSONTyped,
} from './ExamClientQuestionRef';
import type { ExamAttachmentMetaItem } from './ExamAttachmentMetaItem';
import {
    ExamAttachmentMetaItemFromJSON,
    ExamAttachmentMetaItemFromJSONTyped,
    ExamAttachmentMetaItemToJSON,
    ExamAttachmentMetaItemToJSONTyped,
} from './ExamAttachmentMetaItem';

/**
 * 
 * @export
 * @interface ExamAiEditRequest
 */
export interface ExamAiEditRequest {
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditRequest
     */
    message: string;
    /**
     * 
     * @type {ExamAiEditRequestBaseRevision}
     * @memberof ExamAiEditRequest
     */
    baseRevision?: ExamAiEditRequestBaseRevision;
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditRequest
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditRequest
     */
    idempotencyKey?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditRequest
     */
    clientTabId?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ExamAiEditRequest
     */
    fileIds?: Array<number>;
    /**
     * 
     * @type {Array<ExamAttachmentMetaItem>}
     * @memberof ExamAiEditRequest
     */
    attachmentMeta?: Array<ExamAttachmentMetaItem>;
    /**
     * 
     * @type {Array<ExamClientQuestionRef>}
     * @memberof ExamAiEditRequest
     */
    clientQuestions?: Array<ExamClientQuestionRef>;
}

/**
 * Check if a given object implements the ExamAiEditRequest interface.
 */
export function instanceOfExamAiEditRequest(value: object): value is ExamAiEditRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ExamAiEditRequestFromJSON(json: any): ExamAiEditRequest {
    return ExamAiEditRequestFromJSONTyped(json, false);
}

export function ExamAiEditRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamAiEditRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'baseRevision': json['baseRevision'] == null ? undefined : ExamAiEditRequestBaseRevisionFromJSON(json['baseRevision']),
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'idempotencyKey': json['idempotencyKey'] == null ? undefined : json['idempotencyKey'],
        'clientTabId': json['clientTabId'] == null ? undefined : json['clientTabId'],
        'fileIds': json['fileIds'] == null ? undefined : json['fileIds'],
        'attachmentMeta': json['attachmentMeta'] == null ? undefined : ((json['attachmentMeta'] as Array<any>).map(ExamAttachmentMetaItemFromJSON)),
        'clientQuestions': json['clientQuestions'] == null ? undefined : ((json['clientQuestions'] as Array<any>).map(ExamClientQuestionRefFromJSON)),
    };
}

export function ExamAiEditRequestToJSON(json: any): ExamAiEditRequest {
    return ExamAiEditRequestToJSONTyped(json, false);
}

export function ExamAiEditRequestToJSONTyped(value?: ExamAiEditRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'baseRevision': ExamAiEditRequestBaseRevisionToJSON(value['baseRevision']),
        'requestId': value['requestId'],
        'idempotencyKey': value['idempotencyKey'],
        'clientTabId': value['clientTabId'],
        'fileIds': value['fileIds'],
        'attachmentMeta': value['attachmentMeta'] == null ? undefined : ((value['attachmentMeta'] as Array<any>).map(ExamAttachmentMetaItemToJSON)),
        'clientQuestions': value['clientQuestions'] == null ? undefined : ((value['clientQuestions'] as Array<any>).map(ExamClientQuestionRefToJSON)),
    };
}

