/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamQuestionInput } from './ExamQuestionInput';
import {
    ExamQuestionInputFromJSON,
    ExamQuestionInputFromJSONTyped,
    ExamQuestionInputToJSON,
    ExamQuestionInputToJSONTyped,
} from './ExamQuestionInput';

/**
 * 
 * @export
 * @interface ExamsIdQuestionsPutRequest
 */
export interface ExamsIdQuestionsPutRequest {
    /**
     * 
     * @type {Array<ExamQuestionInput>}
     * @memberof ExamsIdQuestionsPutRequest
     */
    questions: Array<ExamQuestionInput>;
}

/**
 * Check if a given object implements the ExamsIdQuestionsPutRequest interface.
 */
export function instanceOfExamsIdQuestionsPutRequest(value: object): value is ExamsIdQuestionsPutRequest {
    if (!('questions' in value) || value['questions'] === undefined) return false;
    return true;
}

export function ExamsIdQuestionsPutRequestFromJSON(json: any): ExamsIdQuestionsPutRequest {
    return ExamsIdQuestionsPutRequestFromJSONTyped(json, false);
}

export function ExamsIdQuestionsPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamsIdQuestionsPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'questions': ((json['questions'] as Array<any>).map(ExamQuestionInputFromJSON)),
    };
}

export function ExamsIdQuestionsPutRequestToJSON(json: any): ExamsIdQuestionsPutRequest {
    return ExamsIdQuestionsPutRequestToJSONTyped(json, false);
}

export function ExamsIdQuestionsPutRequestToJSONTyped(value?: ExamsIdQuestionsPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questions': ((value['questions'] as Array<any>).map(ExamQuestionInputToJSON)),
    };
}

