/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ExamAiEditResponse } from './ExamAiEditResponse';
import {
    instanceOfExamAiEditResponse,
    ExamAiEditResponseFromJSON,
    ExamAiEditResponseFromJSONTyped,
    ExamAiEditResponseToJSON,
} from './ExamAiEditResponse';
import type { ExamChatAiContentOneOf } from './ExamChatAiContentOneOf';
import {
    instanceOfExamChatAiContentOneOf,
    ExamChatAiContentOneOfFromJSON,
    ExamChatAiContentOneOfFromJSONTyped,
    ExamChatAiContentOneOfToJSON,
} from './ExamChatAiContentOneOf';

/**
 * @type ExamChatAiContent
 * 
 * @export
 */
export type ExamChatAiContent = ExamAiEditResponse | ExamChatAiContentOneOf | string;

export function ExamChatAiContentFromJSON(json: any): ExamChatAiContent {
    return ExamChatAiContentFromJSONTyped(json, false);
}

export function ExamChatAiContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamChatAiContent {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfExamAiEditResponse(json)) {
        return ExamAiEditResponseFromJSONTyped(json, true);
    }
    if (instanceOfExamChatAiContentOneOf(json)) {
        return ExamChatAiContentOneOfFromJSONTyped(json, true);
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function ExamChatAiContentToJSON(json: any): any {
    return ExamChatAiContentToJSONTyped(json, false);
}

export function ExamChatAiContentToJSONTyped(value?: ExamChatAiContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfExamAiEditResponse(value)) {
        return ExamAiEditResponseToJSON(value as ExamAiEditResponse);
    }
    if (instanceOfExamChatAiContentOneOf(value)) {
        return ExamChatAiContentOneOfToJSON(value as ExamChatAiContentOneOf);
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

