/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamEditConflict } from './ExamEditConflict';
import {
    ExamEditConflictFromJSON,
    ExamEditConflictFromJSONTyped,
    ExamEditConflictToJSON,
    ExamEditConflictToJSONTyped,
} from './ExamEditConflict';
import type { ExamAiEditsEnvelope } from './ExamAiEditsEnvelope';
import {
    ExamAiEditsEnvelopeFromJSON,
    ExamAiEditsEnvelopeFromJSONTyped,
    ExamAiEditsEnvelopeToJSON,
    ExamAiEditsEnvelopeToJSONTyped,
} from './ExamAiEditsEnvelope';

/**
 * 
 * @export
 * @interface ExamAiEditResponse
 */
export interface ExamAiEditResponse {
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditResponse
     */
    reply: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExamAiEditResponse
     */
    hasEdits: boolean;
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditResponse
     */
    changeSetId: string;
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditResponse
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditResponse
     */
    baseRevision: string;
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditResponse
     */
    resultRevision: string;
    /**
     * 
     * @type {ExamAiEditsEnvelope}
     * @memberof ExamAiEditResponse
     */
    edits: ExamAiEditsEnvelope;
    /**
     * 
     * @type {Array<ExamEditConflict>}
     * @memberof ExamAiEditResponse
     */
    conflicts: Array<ExamEditConflict>;
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditResponse
     */
    checksum: string;
}

/**
 * Check if a given object implements the ExamAiEditResponse interface.
 */
export function instanceOfExamAiEditResponse(value: object): value is ExamAiEditResponse {
    if (!('reply' in value) || value['reply'] === undefined) return false;
    if (!('hasEdits' in value) || value['hasEdits'] === undefined) return false;
    if (!('changeSetId' in value) || value['changeSetId'] === undefined) return false;
    if (!('baseRevision' in value) || value['baseRevision'] === undefined) return false;
    if (!('resultRevision' in value) || value['resultRevision'] === undefined) return false;
    if (!('edits' in value) || value['edits'] === undefined) return false;
    if (!('conflicts' in value) || value['conflicts'] === undefined) return false;
    if (!('checksum' in value) || value['checksum'] === undefined) return false;
    return true;
}

export function ExamAiEditResponseFromJSON(json: any): ExamAiEditResponse {
    return ExamAiEditResponseFromJSONTyped(json, false);
}

export function ExamAiEditResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamAiEditResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reply': json['reply'],
        'hasEdits': json['hasEdits'],
        'changeSetId': json['changeSetId'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'baseRevision': json['baseRevision'],
        'resultRevision': json['resultRevision'],
        'edits': ExamAiEditsEnvelopeFromJSON(json['edits']),
        'conflicts': ((json['conflicts'] as Array<any>).map(ExamEditConflictFromJSON)),
        'checksum': json['checksum'],
    };
}

export function ExamAiEditResponseToJSON(json: any): ExamAiEditResponse {
    return ExamAiEditResponseToJSONTyped(json, false);
}

export function ExamAiEditResponseToJSONTyped(value?: ExamAiEditResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reply': value['reply'],
        'hasEdits': value['hasEdits'],
        'changeSetId': value['changeSetId'],
        'requestId': value['requestId'],
        'baseRevision': value['baseRevision'],
        'resultRevision': value['resultRevision'],
        'edits': ExamAiEditsEnvelopeToJSON(value['edits']),
        'conflicts': ((value['conflicts'] as Array<any>).map(ExamEditConflictToJSON)),
        'checksum': value['checksum'],
    };
}

