/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamQuestionType } from './ExamQuestionType';
import {
    ExamQuestionTypeFromJSON,
    ExamQuestionTypeFromJSONTyped,
    ExamQuestionTypeToJSON,
    ExamQuestionTypeToJSONTyped,
} from './ExamQuestionType';

/**
 * 
 * @export
 * @interface ExamQuestionInput
 */
export interface ExamQuestionInput {
    /**
     * Existing question id for update
     * @type {number}
     * @memberof ExamQuestionInput
     */
    id?: number;
    /**
     * 
     * @type {ExamQuestionType}
     * @memberof ExamQuestionInput
     */
    type: ExamQuestionType;
    /**
     * 
     * @type {number}
     * @memberof ExamQuestionInput
     */
    order: number;
    /**
     * 
     * @type {string}
     * @memberof ExamQuestionInput
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExamQuestionInput
     */
    description?: string | null;
    /**
     * 
     * @type {any}
     * @memberof ExamQuestionInput
     */
    spec: any | null;
    /**
     * Null for short_answer / long_answer / fill_in_the_blank
     * @type {any}
     * @memberof ExamQuestionInput
     */
    correctAnswer?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ExamQuestionInput
     */
    rubric?: string;
    /**
     * 
     * @type {number}
     * @memberof ExamQuestionInput
     */
    maxPoints: number;
}



/**
 * Check if a given object implements the ExamQuestionInput interface.
 */
export function instanceOfExamQuestionInput(value: object): value is ExamQuestionInput {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    if (!('maxPoints' in value) || value['maxPoints'] === undefined) return false;
    return true;
}

export function ExamQuestionInputFromJSON(json: any): ExamQuestionInput {
    return ExamQuestionInputFromJSONTyped(json, false);
}

export function ExamQuestionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamQuestionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': ExamQuestionTypeFromJSON(json['type']),
        'order': json['order'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'spec': json['spec'],
        'correctAnswer': json['correctAnswer'] == null ? undefined : json['correctAnswer'],
        'rubric': json['rubric'] == null ? undefined : json['rubric'],
        'maxPoints': json['maxPoints'],
    };
}

export function ExamQuestionInputToJSON(json: any): ExamQuestionInput {
    return ExamQuestionInputToJSONTyped(json, false);
}

export function ExamQuestionInputToJSONTyped(value?: ExamQuestionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': ExamQuestionTypeToJSON(value['type']),
        'order': value['order'],
        'title': value['title'],
        'description': value['description'],
        'spec': value['spec'],
        'correctAnswer': value['correctAnswer'],
        'rubric': value['rubric'],
        'maxPoints': value['maxPoints'],
    };
}

