/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamLinkIdPostRequest
 */
export interface ExamLinkIdPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ExamLinkIdPostRequest
     */
    fileId: number;
}

/**
 * Check if a given object implements the ExamLinkIdPostRequest interface.
 */
export function instanceOfExamLinkIdPostRequest(value: object): value is ExamLinkIdPostRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function ExamLinkIdPostRequestFromJSON(json: any): ExamLinkIdPostRequest {
    return ExamLinkIdPostRequestFromJSONTyped(json, false);
}

export function ExamLinkIdPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamLinkIdPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['fileId'],
    };
}

export function ExamLinkIdPostRequestToJSON(json: any): ExamLinkIdPostRequest {
    return ExamLinkIdPostRequestToJSONTyped(json, false);
}

export function ExamLinkIdPostRequestToJSONTyped(value?: ExamLinkIdPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileId': value['fileId'],
    };
}

