/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamAttachmentMetaItem
 */
export interface ExamAttachmentMetaItem {
    /**
     * 
     * @type {number}
     * @memberof ExamAttachmentMetaItem
     */
    fileId: number;
    /**
     * 
     * @type {string}
     * @memberof ExamAttachmentMetaItem
     */
    kind?: ExamAttachmentMetaItemKindEnum;
    /**
     * 
     * @type {number}
     * @memberof ExamAttachmentMetaItem
     */
    draftId?: number;
}


/**
 * @export
 */
export const ExamAttachmentMetaItemKindEnum = {
    File: 'file',
    Draft: 'draft'
} as const;
export type ExamAttachmentMetaItemKindEnum = typeof ExamAttachmentMetaItemKindEnum[keyof typeof ExamAttachmentMetaItemKindEnum];


/**
 * Check if a given object implements the ExamAttachmentMetaItem interface.
 */
export function instanceOfExamAttachmentMetaItem(value: object): value is ExamAttachmentMetaItem {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function ExamAttachmentMetaItemFromJSON(json: any): ExamAttachmentMetaItem {
    return ExamAttachmentMetaItemFromJSONTyped(json, false);
}

export function ExamAttachmentMetaItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamAttachmentMetaItem {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['fileId'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'draftId': json['draftId'] == null ? undefined : json['draftId'],
    };
}

export function ExamAttachmentMetaItemToJSON(json: any): ExamAttachmentMetaItem {
    return ExamAttachmentMetaItemToJSONTyped(json, false);
}

export function ExamAttachmentMetaItemToJSONTyped(value?: ExamAttachmentMetaItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileId': value['fileId'],
        'kind': value['kind'],
        'draftId': value['draftId'],
    };
}

