/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamClientQuestionRef
 */
export interface ExamClientQuestionRef {
    /**
     * 
     * @type {string}
     * @memberof ExamClientQuestionRef
     */
    clientId: string;
    /**
     * 
     * @type {number}
     * @memberof ExamClientQuestionRef
     */
    serverId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExamClientQuestionRef
     */
    questionId?: number | null;
}

/**
 * Check if a given object implements the ExamClientQuestionRef interface.
 */
export function instanceOfExamClientQuestionRef(value: object): value is ExamClientQuestionRef {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    return true;
}

export function ExamClientQuestionRefFromJSON(json: any): ExamClientQuestionRef {
    return ExamClientQuestionRefFromJSONTyped(json, false);
}

export function ExamClientQuestionRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamClientQuestionRef {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['clientId'],
        'serverId': json['serverId'] == null ? undefined : json['serverId'],
        'questionId': json['questionId'] == null ? undefined : json['questionId'],
    };
}

export function ExamClientQuestionRefToJSON(json: any): ExamClientQuestionRef {
    return ExamClientQuestionRefToJSONTyped(json, false);
}

export function ExamClientQuestionRefToJSONTyped(value?: ExamClientQuestionRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientId': value['clientId'],
        'serverId': value['serverId'],
        'questionId': value['questionId'],
    };
}

