/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamChatsIdMessagesMessageIdPatch200Response
 */
export interface ExamChatsIdMessagesMessageIdPatch200Response {
    /**
     * 
     * @type {number}
     * @memberof ExamChatsIdMessagesMessageIdPatch200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ExamChatsIdMessagesMessageIdPatch200Response
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof ExamChatsIdMessagesMessageIdPatch200Response
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ExamChatsIdMessagesMessageIdPatch200Response interface.
 */
export function instanceOfExamChatsIdMessagesMessageIdPatch200Response(value: object): value is ExamChatsIdMessagesMessageIdPatch200Response {
    return true;
}

export function ExamChatsIdMessagesMessageIdPatch200ResponseFromJSON(json: any): ExamChatsIdMessagesMessageIdPatch200Response {
    return ExamChatsIdMessagesMessageIdPatch200ResponseFromJSONTyped(json, false);
}

export function ExamChatsIdMessagesMessageIdPatch200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamChatsIdMessagesMessageIdPatch200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ExamChatsIdMessagesMessageIdPatch200ResponseToJSON(json: any): ExamChatsIdMessagesMessageIdPatch200Response {
    return ExamChatsIdMessagesMessageIdPatch200ResponseToJSONTyped(json, false);
}

export function ExamChatsIdMessagesMessageIdPatch200ResponseToJSONTyped(value?: ExamChatsIdMessagesMessageIdPatch200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

