/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamQuestionEdit } from './ExamQuestionEdit';
import {
    ExamQuestionEditFromJSON,
    ExamQuestionEditFromJSONTyped,
    ExamQuestionEditToJSON,
    ExamQuestionEditToJSONTyped,
} from './ExamQuestionEdit';
import type { ExamMetaEdits } from './ExamMetaEdits';
import {
    ExamMetaEditsFromJSON,
    ExamMetaEditsFromJSONTyped,
    ExamMetaEditsToJSON,
    ExamMetaEditsToJSONTyped,
} from './ExamMetaEdits';

/**
 * 
 * @export
 * @interface ExamAiEditsEnvelope
 */
export interface ExamAiEditsEnvelope {
    /**
     * 
     * @type {string}
     * @memberof ExamAiEditsEnvelope
     */
    status: ExamAiEditsEnvelopeStatusEnum;
    /**
     * 
     * @type {Array<ExamQuestionEdit>}
     * @memberof ExamAiEditsEnvelope
     */
    questionEdits: Array<ExamQuestionEdit>;
    /**
     * 
     * @type {ExamMetaEdits}
     * @memberof ExamAiEditsEnvelope
     */
    examMetaEdits?: ExamMetaEdits;
}


/**
 * @export
 */
export const ExamAiEditsEnvelopeStatusEnum = {
    Pending: 'pending',
    Applied: 'applied',
    Rejected: 'rejected'
} as const;
export type ExamAiEditsEnvelopeStatusEnum = typeof ExamAiEditsEnvelopeStatusEnum[keyof typeof ExamAiEditsEnvelopeStatusEnum];


/**
 * Check if a given object implements the ExamAiEditsEnvelope interface.
 */
export function instanceOfExamAiEditsEnvelope(value: object): value is ExamAiEditsEnvelope {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('questionEdits' in value) || value['questionEdits'] === undefined) return false;
    return true;
}

export function ExamAiEditsEnvelopeFromJSON(json: any): ExamAiEditsEnvelope {
    return ExamAiEditsEnvelopeFromJSONTyped(json, false);
}

export function ExamAiEditsEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamAiEditsEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'questionEdits': ((json['questionEdits'] as Array<any>).map(ExamQuestionEditFromJSON)),
        'examMetaEdits': json['examMetaEdits'] == null ? undefined : ExamMetaEditsFromJSON(json['examMetaEdits']),
    };
}

export function ExamAiEditsEnvelopeToJSON(json: any): ExamAiEditsEnvelope {
    return ExamAiEditsEnvelopeToJSONTyped(json, false);
}

export function ExamAiEditsEnvelopeToJSONTyped(value?: ExamAiEditsEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'questionEdits': ((value['questionEdits'] as Array<any>).map(ExamQuestionEditToJSON)),
        'examMetaEdits': ExamMetaEditsToJSON(value['examMetaEdits']),
    };
}

