/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamMetaEdits
 */
export interface ExamMetaEdits {
    /**
     * 
     * @type {string}
     * @memberof ExamMetaEdits
     */
    titleYaml?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamMetaEdits
     */
    rubricYaml?: string;
}

/**
 * Check if a given object implements the ExamMetaEdits interface.
 */
export function instanceOfExamMetaEdits(value: object): value is ExamMetaEdits {
    return true;
}

export function ExamMetaEditsFromJSON(json: any): ExamMetaEdits {
    return ExamMetaEditsFromJSONTyped(json, false);
}

export function ExamMetaEditsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamMetaEdits {
    if (json == null) {
        return json;
    }
    return {
        
        'titleYaml': json['titleYaml'] == null ? undefined : json['titleYaml'],
        'rubricYaml': json['rubricYaml'] == null ? undefined : json['rubricYaml'],
    };
}

export function ExamMetaEditsToJSON(json: any): ExamMetaEdits {
    return ExamMetaEditsToJSONTyped(json, false);
}

export function ExamMetaEditsToJSONTyped(value?: ExamMetaEdits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'titleYaml': value['titleYaml'],
        'rubricYaml': value['rubricYaml'],
    };
}

