/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamsIdSubmissionsPostRequestAnswersInner
 */
export interface ExamsIdSubmissionsPostRequestAnswersInner {
    /**
     * 
     * @type {number}
     * @memberof ExamsIdSubmissionsPostRequestAnswersInner
     */
    questionId: number;
    /**
     * 
     * @type {any}
     * @memberof ExamsIdSubmissionsPostRequestAnswersInner
     */
    answer: any | null;
}

/**
 * Check if a given object implements the ExamsIdSubmissionsPostRequestAnswersInner interface.
 */
export function instanceOfExamsIdSubmissionsPostRequestAnswersInner(value: object): value is ExamsIdSubmissionsPostRequestAnswersInner {
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('answer' in value) || value['answer'] === undefined) return false;
    return true;
}

export function ExamsIdSubmissionsPostRequestAnswersInnerFromJSON(json: any): ExamsIdSubmissionsPostRequestAnswersInner {
    return ExamsIdSubmissionsPostRequestAnswersInnerFromJSONTyped(json, false);
}

export function ExamsIdSubmissionsPostRequestAnswersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamsIdSubmissionsPostRequestAnswersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['questionId'],
        'answer': json['answer'],
    };
}

export function ExamsIdSubmissionsPostRequestAnswersInnerToJSON(json: any): ExamsIdSubmissionsPostRequestAnswersInner {
    return ExamsIdSubmissionsPostRequestAnswersInnerToJSONTyped(json, false);
}

export function ExamsIdSubmissionsPostRequestAnswersInnerToJSONTyped(value?: ExamsIdSubmissionsPostRequestAnswersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionId': value['questionId'],
        'answer': value['answer'],
    };
}

