/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamsIdPutRequest
 */
export interface ExamsIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof ExamsIdPutRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamsIdPutRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExamsIdPutRequest
     */
    rubric?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ExamsIdPutRequest
     */
    isPublished?: boolean;
}

/**
 * Check if a given object implements the ExamsIdPutRequest interface.
 */
export function instanceOfExamsIdPutRequest(value: object): value is ExamsIdPutRequest {
    return true;
}

export function ExamsIdPutRequestFromJSON(json: any): ExamsIdPutRequest {
    return ExamsIdPutRequestFromJSONTyped(json, false);
}

export function ExamsIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamsIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'rubric': json['rubric'] == null ? undefined : json['rubric'],
        'isPublished': json['isPublished'] == null ? undefined : json['isPublished'],
    };
}

export function ExamsIdPutRequestToJSON(json: any): ExamsIdPutRequest {
    return ExamsIdPutRequestToJSONTyped(json, false);
}

export function ExamsIdPutRequestToJSONTyped(value?: ExamsIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'rubric': value['rubric'],
        'isPublished': value['isPublished'],
    };
}

