/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExamQuestionType = {
    Radio: 'radio',
    Checkbox: 'checkbox',
    TrueFalse: 'true_false',
    Matching: 'matching',
    Ordering: 'ordering',
    Grouping: 'grouping',
    FillInTheBlank: 'fill_in_the_blank',
    ShortAnswer: 'short_answer',
    LongAnswer: 'long_answer'
} as const;
export type ExamQuestionType = typeof ExamQuestionType[keyof typeof ExamQuestionType];


export function instanceOfExamQuestionType(value: any): boolean {
    for (const key in ExamQuestionType) {
        if (Object.prototype.hasOwnProperty.call(ExamQuestionType, key)) {
            if (ExamQuestionType[key as keyof typeof ExamQuestionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExamQuestionTypeFromJSON(json: any): ExamQuestionType {
    return ExamQuestionTypeFromJSONTyped(json, false);
}

export function ExamQuestionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamQuestionType {
    return json as ExamQuestionType;
}

export function ExamQuestionTypeToJSON(value?: ExamQuestionType | null): any {
    return value as any;
}

export function ExamQuestionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ExamQuestionType {
    return value as ExamQuestionType;
}

