/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ExamAiEditRequestBaseRevision
 * Client exam.updatedAt revision used for stale proposal detection.
 * @export
 */
export type ExamAiEditRequestBaseRevision = number | string;

export function ExamAiEditRequestBaseRevisionFromJSON(json: any): ExamAiEditRequestBaseRevision {
    return ExamAiEditRequestBaseRevisionFromJSONTyped(json, false);
}

export function ExamAiEditRequestBaseRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamAiEditRequestBaseRevision {
    if (json == null) {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function ExamAiEditRequestBaseRevisionToJSON(json: any): any {
    return ExamAiEditRequestBaseRevisionToJSONTyped(json, false);
}

export function ExamAiEditRequestBaseRevisionToJSONTyped(value?: ExamAiEditRequestBaseRevision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

