/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamsPostRequest
 */
export interface ExamsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ExamsPostRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ExamsPostRequest
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExamsPostRequest
     */
    subjectId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExamsPostRequest
     */
    schoolClassId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ExamsPostRequest
     */
    rubric?: string | null;
}

/**
 * Check if a given object implements the ExamsPostRequest interface.
 */
export function instanceOfExamsPostRequest(value: object): value is ExamsPostRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ExamsPostRequestFromJSON(json: any): ExamsPostRequest {
    return ExamsPostRequestFromJSONTyped(json, false);
}

export function ExamsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'subjectId': json['subjectId'] == null ? undefined : json['subjectId'],
        'schoolClassId': json['schoolClassId'] == null ? undefined : json['schoolClassId'],
        'rubric': json['rubric'] == null ? undefined : json['rubric'],
    };
}

export function ExamsPostRequestToJSON(json: any): ExamsPostRequest {
    return ExamsPostRequestToJSONTyped(json, false);
}

export function ExamsPostRequestToJSONTyped(value?: ExamsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'subjectId': value['subjectId'],
        'schoolClassId': value['schoolClassId'],
        'rubric': value['rubric'],
    };
}

