/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamChatAiContentOneOf
 */
export interface ExamChatAiContentOneOf {
    /**
     * 
     * @type {string}
     * @memberof ExamChatAiContentOneOf
     */
    reply?: string;
}

/**
 * Check if a given object implements the ExamChatAiContentOneOf interface.
 */
export function instanceOfExamChatAiContentOneOf(value: object): value is ExamChatAiContentOneOf {
    return true;
}

export function ExamChatAiContentOneOfFromJSON(json: any): ExamChatAiContentOneOf {
    return ExamChatAiContentOneOfFromJSONTyped(json, false);
}

export function ExamChatAiContentOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamChatAiContentOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'reply': json['reply'] == null ? undefined : json['reply'],
    };
}

export function ExamChatAiContentOneOfToJSON(json: any): ExamChatAiContentOneOf {
    return ExamChatAiContentOneOfToJSONTyped(json, false);
}

export function ExamChatAiContentOneOfToJSONTyped(value?: ExamChatAiContentOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reply': value['reply'],
    };
}

