/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamChatAiContent } from './ExamChatAiContent';
import {
    ExamChatAiContentFromJSON,
    ExamChatAiContentFromJSONTyped,
    ExamChatAiContentToJSON,
    ExamChatAiContentToJSONTyped,
} from './ExamChatAiContent';
import type { ExamChatMessageAttachedFilesInner } from './ExamChatMessageAttachedFilesInner';
import {
    ExamChatMessageAttachedFilesInnerFromJSON,
    ExamChatMessageAttachedFilesInnerFromJSONTyped,
    ExamChatMessageAttachedFilesInnerToJSON,
    ExamChatMessageAttachedFilesInnerToJSONTyped,
} from './ExamChatMessageAttachedFilesInner';

/**
 * 
 * @export
 * @interface ExamChatMessage
 */
export interface ExamChatMessage {
    /**
     * 
     * @type {string}
     * @memberof ExamChatMessage
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamChatMessage
     */
    role?: ExamChatMessageRoleEnum;
    /**
     * 
     * @type {ExamChatAiContent}
     * @memberof ExamChatMessage
     */
    content?: ExamChatAiContent;
    /**
     * 
     * @type {Date}
     * @memberof ExamChatMessage
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof ExamChatMessage
     */
    idempotencyKey?: string;
    /**
     * 
     * @type {Array<ExamChatMessageAttachedFilesInner>}
     * @memberof ExamChatMessage
     */
    attachedFiles?: Array<ExamChatMessageAttachedFilesInner>;
}


/**
 * @export
 */
export const ExamChatMessageRoleEnum = {
    User: 'user',
    Ai: 'ai',
    Model: 'model',
    System: 'system'
} as const;
export type ExamChatMessageRoleEnum = typeof ExamChatMessageRoleEnum[keyof typeof ExamChatMessageRoleEnum];


/**
 * Check if a given object implements the ExamChatMessage interface.
 */
export function instanceOfExamChatMessage(value: object): value is ExamChatMessage {
    return true;
}

export function ExamChatMessageFromJSON(json: any): ExamChatMessage {
    return ExamChatMessageFromJSONTyped(json, false);
}

export function ExamChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamChatMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'] == null ? undefined : ExamChatAiContentFromJSON(json['content']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'idempotencyKey': json['idempotencyKey'] == null ? undefined : json['idempotencyKey'],
        'attachedFiles': json['attachedFiles'] == null ? undefined : ((json['attachedFiles'] as Array<any>).map(ExamChatMessageAttachedFilesInnerFromJSON)),
    };
}

export function ExamChatMessageToJSON(json: any): ExamChatMessage {
    return ExamChatMessageToJSONTyped(json, false);
}

export function ExamChatMessageToJSONTyped(value?: ExamChatMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role': value['role'],
        'content': ExamChatAiContentToJSON(value['content']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'idempotencyKey': value['idempotencyKey'],
        'attachedFiles': value['attachedFiles'] == null ? undefined : ((value['attachedFiles'] as Array<any>).map(ExamChatMessageAttachedFilesInnerToJSON)),
    };
}

