/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamChatMessageAttachedFilesInner
 */
export interface ExamChatMessageAttachedFilesInner {
    /**
     * 
     * @type {number}
     * @memberof ExamChatMessageAttachedFilesInner
     */
    fileId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExamChatMessageAttachedFilesInner
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamChatMessageAttachedFilesInner
     */
    kind?: ExamChatMessageAttachedFilesInnerKindEnum;
    /**
     * 
     * @type {number}
     * @memberof ExamChatMessageAttachedFilesInner
     */
    draftId?: number;
}


/**
 * @export
 */
export const ExamChatMessageAttachedFilesInnerKindEnum = {
    File: 'file',
    Draft: 'draft'
} as const;
export type ExamChatMessageAttachedFilesInnerKindEnum = typeof ExamChatMessageAttachedFilesInnerKindEnum[keyof typeof ExamChatMessageAttachedFilesInnerKindEnum];


/**
 * Check if a given object implements the ExamChatMessageAttachedFilesInner interface.
 */
export function instanceOfExamChatMessageAttachedFilesInner(value: object): value is ExamChatMessageAttachedFilesInner {
    return true;
}

export function ExamChatMessageAttachedFilesInnerFromJSON(json: any): ExamChatMessageAttachedFilesInner {
    return ExamChatMessageAttachedFilesInnerFromJSONTyped(json, false);
}

export function ExamChatMessageAttachedFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamChatMessageAttachedFilesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['fileId'] == null ? undefined : json['fileId'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'draftId': json['draftId'] == null ? undefined : json['draftId'],
    };
}

export function ExamChatMessageAttachedFilesInnerToJSON(json: any): ExamChatMessageAttachedFilesInner {
    return ExamChatMessageAttachedFilesInnerToJSONTyped(json, false);
}

export function ExamChatMessageAttachedFilesInnerToJSONTyped(value?: ExamChatMessageAttachedFilesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileId': value['fileId'],
        'filename': value['filename'],
        'kind': value['kind'],
        'draftId': value['draftId'],
    };
}

