/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamChatMessage } from './ExamChatMessage';
import {
    ExamChatMessageFromJSON,
    ExamChatMessageFromJSONTyped,
    ExamChatMessageToJSON,
    ExamChatMessageToJSONTyped,
} from './ExamChatMessage';

/**
 * 
 * @export
 * @interface ExamChatsIdGet200Response
 */
export interface ExamChatsIdGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ExamChatsIdGet200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ExamChatsIdGet200Response
     */
    message?: string;
    /**
     * 
     * @type {Array<ExamChatMessage>}
     * @memberof ExamChatsIdGet200Response
     */
    messages?: Array<ExamChatMessage>;
    /**
     * 
     * @type {Date}
     * @memberof ExamChatsIdGet200Response
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the ExamChatsIdGet200Response interface.
 */
export function instanceOfExamChatsIdGet200Response(value: object): value is ExamChatsIdGet200Response {
    return true;
}

export function ExamChatsIdGet200ResponseFromJSON(json: any): ExamChatsIdGet200Response {
    return ExamChatsIdGet200ResponseFromJSONTyped(json, false);
}

export function ExamChatsIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamChatsIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(ExamChatMessageFromJSON)),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ExamChatsIdGet200ResponseToJSON(json: any): ExamChatsIdGet200Response {
    return ExamChatsIdGet200ResponseToJSONTyped(json, false);
}

export function ExamChatsIdGet200ResponseToJSONTyped(value?: ExamChatsIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(ExamChatMessageToJSON)),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

