/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamChatMessagePatchRequest
 */
export interface ExamChatMessagePatchRequest {
    /**
     * 
     * @type {string}
     * @memberof ExamChatMessagePatchRequest
     */
    status: ExamChatMessagePatchRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ExamChatMessagePatchRequest
     */
    clientTabId?: string;
}


/**
 * @export
 */
export const ExamChatMessagePatchRequestStatusEnum = {
    Pending: 'pending',
    Applied: 'applied',
    Rejected: 'rejected'
} as const;
export type ExamChatMessagePatchRequestStatusEnum = typeof ExamChatMessagePatchRequestStatusEnum[keyof typeof ExamChatMessagePatchRequestStatusEnum];


/**
 * Check if a given object implements the ExamChatMessagePatchRequest interface.
 */
export function instanceOfExamChatMessagePatchRequest(value: object): value is ExamChatMessagePatchRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ExamChatMessagePatchRequestFromJSON(json: any): ExamChatMessagePatchRequest {
    return ExamChatMessagePatchRequestFromJSONTyped(json, false);
}

export function ExamChatMessagePatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamChatMessagePatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'clientTabId': json['clientTabId'] == null ? undefined : json['clientTabId'],
    };
}

export function ExamChatMessagePatchRequestToJSON(json: any): ExamChatMessagePatchRequest {
    return ExamChatMessagePatchRequestToJSONTyped(json, false);
}

export function ExamChatMessagePatchRequestToJSONTyped(value?: ExamChatMessagePatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'clientTabId': value['clientTabId'],
    };
}

