/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamsIdAttachDraftPostRequest
 */
export interface ExamsIdAttachDraftPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ExamsIdAttachDraftPostRequest
     */
    draftId: number;
}

/**
 * Check if a given object implements the ExamsIdAttachDraftPostRequest interface.
 */
export function instanceOfExamsIdAttachDraftPostRequest(value: object): value is ExamsIdAttachDraftPostRequest {
    if (!('draftId' in value) || value['draftId'] === undefined) return false;
    return true;
}

export function ExamsIdAttachDraftPostRequestFromJSON(json: any): ExamsIdAttachDraftPostRequest {
    return ExamsIdAttachDraftPostRequestFromJSONTyped(json, false);
}

export function ExamsIdAttachDraftPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamsIdAttachDraftPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'draftId': json['draftId'],
    };
}

export function ExamsIdAttachDraftPostRequestToJSON(json: any): ExamsIdAttachDraftPostRequest {
    return ExamsIdAttachDraftPostRequestToJSONTyped(json, false);
}

export function ExamsIdAttachDraftPostRequestToJSONTyped(value?: ExamsIdAttachDraftPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'draftId': value['draftId'],
    };
}

