/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamsIdSubmissionsPostRequestAnswersInner } from './ExamsIdSubmissionsPostRequestAnswersInner';
import {
    ExamsIdSubmissionsPostRequestAnswersInnerFromJSON,
    ExamsIdSubmissionsPostRequestAnswersInnerFromJSONTyped,
    ExamsIdSubmissionsPostRequestAnswersInnerToJSON,
    ExamsIdSubmissionsPostRequestAnswersInnerToJSONTyped,
} from './ExamsIdSubmissionsPostRequestAnswersInner';

/**
 * 
 * @export
 * @interface ExamsIdSubmissionsPostRequest
 */
export interface ExamsIdSubmissionsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ExamsIdSubmissionsPostRequest
     */
    digitizedFrom: ExamsIdSubmissionsPostRequestDigitizedFromEnum;
    /**
     * 
     * @type {number}
     * @memberof ExamsIdSubmissionsPostRequest
     */
    studentId?: number | null;
    /**
     * 
     * @type {Array<ExamsIdSubmissionsPostRequestAnswersInner>}
     * @memberof ExamsIdSubmissionsPostRequest
     */
    answers?: Array<ExamsIdSubmissionsPostRequestAnswersInner>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ExamsIdSubmissionsPostRequest
     */
    pageFileIds?: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof ExamsIdSubmissionsPostRequest
     */
    runDigitize?: boolean;
}


/**
 * @export
 */
export const ExamsIdSubmissionsPostRequestDigitizedFromEnum = {
    Manual: 'manual',
    Ocr: 'ocr'
} as const;
export type ExamsIdSubmissionsPostRequestDigitizedFromEnum = typeof ExamsIdSubmissionsPostRequestDigitizedFromEnum[keyof typeof ExamsIdSubmissionsPostRequestDigitizedFromEnum];


/**
 * Check if a given object implements the ExamsIdSubmissionsPostRequest interface.
 */
export function instanceOfExamsIdSubmissionsPostRequest(value: object): value is ExamsIdSubmissionsPostRequest {
    if (!('digitizedFrom' in value) || value['digitizedFrom'] === undefined) return false;
    return true;
}

export function ExamsIdSubmissionsPostRequestFromJSON(json: any): ExamsIdSubmissionsPostRequest {
    return ExamsIdSubmissionsPostRequestFromJSONTyped(json, false);
}

export function ExamsIdSubmissionsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamsIdSubmissionsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'digitizedFrom': json['digitizedFrom'],
        'studentId': json['studentId'] == null ? undefined : json['studentId'],
        'answers': json['answers'] == null ? undefined : ((json['answers'] as Array<any>).map(ExamsIdSubmissionsPostRequestAnswersInnerFromJSON)),
        'pageFileIds': json['pageFileIds'] == null ? undefined : json['pageFileIds'],
        'runDigitize': json['runDigitize'] == null ? undefined : json['runDigitize'],
    };
}

export function ExamsIdSubmissionsPostRequestToJSON(json: any): ExamsIdSubmissionsPostRequest {
    return ExamsIdSubmissionsPostRequestToJSONTyped(json, false);
}

export function ExamsIdSubmissionsPostRequestToJSONTyped(value?: ExamsIdSubmissionsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'digitizedFrom': value['digitizedFrom'],
        'studentId': value['studentId'],
        'answers': value['answers'] == null ? undefined : ((value['answers'] as Array<any>).map(ExamsIdSubmissionsPostRequestAnswersInnerToJSON)),
        'pageFileIds': value['pageFileIds'],
        'runDigitize': value['runDigitize'],
    };
}

