/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamEditConflict
 */
export interface ExamEditConflict {
    /**
     * 
     * @type {string}
     * @memberof ExamEditConflict
     */
    code: ExamEditConflictCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof ExamEditConflict
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ExamEditConflict
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamEditConflict
     */
    clientId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExamEditConflict
     */
    expectedRevision?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamEditConflict
     */
    actualRevision?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamEditConflict
     */
    hint?: string;
}


/**
 * @export
 */
export const ExamEditConflictCodeEnum = {
    StaleRevision: 'stale_revision',
    InvalidTarget: 'invalid_target',
    InvalidPayload: 'invalid_payload',
    InvalidYaml: 'invalid_yaml'
} as const;
export type ExamEditConflictCodeEnum = typeof ExamEditConflictCodeEnum[keyof typeof ExamEditConflictCodeEnum];


/**
 * Check if a given object implements the ExamEditConflict interface.
 */
export function instanceOfExamEditConflict(value: object): value is ExamEditConflict {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ExamEditConflictFromJSON(json: any): ExamEditConflict {
    return ExamEditConflictFromJSONTyped(json, false);
}

export function ExamEditConflictFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamEditConflict {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'operationId': json['operationId'] == null ? undefined : json['operationId'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'expectedRevision': json['expectedRevision'] == null ? undefined : json['expectedRevision'],
        'actualRevision': json['actualRevision'] == null ? undefined : json['actualRevision'],
        'hint': json['hint'] == null ? undefined : json['hint'],
    };
}

export function ExamEditConflictToJSON(json: any): ExamEditConflict {
    return ExamEditConflictToJSONTyped(json, false);
}

export function ExamEditConflictToJSONTyped(value?: ExamEditConflict | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'operationId': value['operationId'],
        'clientId': value['clientId'],
        'expectedRevision': value['expectedRevision'],
        'actualRevision': value['actualRevision'],
        'hint': value['hint'],
    };
}

