/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamAiEditResponse } from './ExamAiEditResponse';
import {
    ExamAiEditResponseFromJSON,
    ExamAiEditResponseFromJSONTyped,
    ExamAiEditResponseToJSON,
    ExamAiEditResponseToJSONTyped,
} from './ExamAiEditResponse';

/**
 * 
 * @export
 * @interface ExamChatsIdPost200Response
 */
export interface ExamChatsIdPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ExamChatsIdPost200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ExamChatsIdPost200Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamChatsIdPost200Response
     */
    reply?: string;
    /**
     * 
     * @type {ExamAiEditResponse}
     * @memberof ExamChatsIdPost200Response
     */
    response?: ExamAiEditResponse;
}

/**
 * Check if a given object implements the ExamChatsIdPost200Response interface.
 */
export function instanceOfExamChatsIdPost200Response(value: object): value is ExamChatsIdPost200Response {
    return true;
}

export function ExamChatsIdPost200ResponseFromJSON(json: any): ExamChatsIdPost200Response {
    return ExamChatsIdPost200ResponseFromJSONTyped(json, false);
}

export function ExamChatsIdPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamChatsIdPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'reply': json['reply'] == null ? undefined : json['reply'],
        'response': json['response'] == null ? undefined : ExamAiEditResponseFromJSON(json['response']),
    };
}

export function ExamChatsIdPost200ResponseToJSON(json: any): ExamChatsIdPost200Response {
    return ExamChatsIdPost200ResponseToJSONTyped(json, false);
}

export function ExamChatsIdPost200ResponseToJSONTyped(value?: ExamChatsIdPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'reply': value['reply'],
        'response': ExamAiEditResponseToJSON(value['response']),
    };
}

