/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExamChatsIdPostRequest
 */
export interface ExamChatsIdPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ExamChatsIdPostRequest
     */
    message: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ExamChatsIdPostRequest
     */
    fileIds?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof ExamChatsIdPostRequest
     */
    idempotencyKey?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamChatsIdPostRequest
     */
    clientTabId?: string;
}

/**
 * Check if a given object implements the ExamChatsIdPostRequest interface.
 */
export function instanceOfExamChatsIdPostRequest(value: object): value is ExamChatsIdPostRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ExamChatsIdPostRequestFromJSON(json: any): ExamChatsIdPostRequest {
    return ExamChatsIdPostRequestFromJSONTyped(json, false);
}

export function ExamChatsIdPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamChatsIdPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'fileIds': json['fileIds'] == null ? undefined : json['fileIds'],
        'idempotencyKey': json['idempotencyKey'] == null ? undefined : json['idempotencyKey'],
        'clientTabId': json['clientTabId'] == null ? undefined : json['clientTabId'],
    };
}

export function ExamChatsIdPostRequestToJSON(json: any): ExamChatsIdPostRequest {
    return ExamChatsIdPostRequestToJSONTyped(json, false);
}

export function ExamChatsIdPostRequestToJSONTyped(value?: ExamChatsIdPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'fileIds': value['fileIds'],
        'idempotencyKey': value['idempotencyKey'],
        'clientTabId': value['clientTabId'],
    };
}

