/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamAiEditResponse } from './ExamAiEditResponse';
import {
    ExamAiEditResponseFromJSON,
    ExamAiEditResponseFromJSONTyped,
    ExamAiEditResponseToJSON,
    ExamAiEditResponseToJSONTyped,
} from './ExamAiEditResponse';

/**
 * 
 * @export
 * @interface ExamsIdAiEditsPost200Response
 */
export interface ExamsIdAiEditsPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ExamsIdAiEditsPost200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ExamsIdAiEditsPost200Response
     */
    message?: string;
    /**
     * 
     * @type {ExamAiEditResponse}
     * @memberof ExamsIdAiEditsPost200Response
     */
    response?: ExamAiEditResponse;
    /**
     * 
     * @type {string}
     * @memberof ExamsIdAiEditsPost200Response
     */
    reply?: string;
    /**
     * 
     * @type {Date}
     * @memberof ExamsIdAiEditsPost200Response
     */
    chatUpdatedAt?: Date;
}

/**
 * Check if a given object implements the ExamsIdAiEditsPost200Response interface.
 */
export function instanceOfExamsIdAiEditsPost200Response(value: object): value is ExamsIdAiEditsPost200Response {
    return true;
}

export function ExamsIdAiEditsPost200ResponseFromJSON(json: any): ExamsIdAiEditsPost200Response {
    return ExamsIdAiEditsPost200ResponseFromJSONTyped(json, false);
}

export function ExamsIdAiEditsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamsIdAiEditsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'response': json['response'] == null ? undefined : ExamAiEditResponseFromJSON(json['response']),
        'reply': json['reply'] == null ? undefined : json['reply'],
        'chatUpdatedAt': json['chatUpdatedAt'] == null ? undefined : (new Date(json['chatUpdatedAt'])),
    };
}

export function ExamsIdAiEditsPost200ResponseToJSON(json: any): ExamsIdAiEditsPost200Response {
    return ExamsIdAiEditsPost200ResponseToJSONTyped(json, false);
}

export function ExamsIdAiEditsPost200ResponseToJSONTyped(value?: ExamsIdAiEditsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'response': ExamAiEditResponseToJSON(value['response']),
        'reply': value['reply'],
        'chatUpdatedAt': value['chatUpdatedAt'] == null ? value['chatUpdatedAt'] : value['chatUpdatedAt'].toISOString(),
    };
}

