/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FreeQueryRequest
 */
export interface FreeQueryRequest {
    /**
     * The prompt to send to the AI model
     * @type {string}
     * @memberof FreeQueryRequest
     */
    prompt: string;
    /**
     * Gemini model to use (defaults to gemini-2.0-flash)
     * @type {string}
     * @memberof FreeQueryRequest
     */
    model?: string;
}

/**
 * Check if a given object implements the FreeQueryRequest interface.
 */
export function instanceOfFreeQueryRequest(value: object): value is FreeQueryRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function FreeQueryRequestFromJSON(json: any): FreeQueryRequest {
    return FreeQueryRequestFromJSONTyped(json, false);
}

export function FreeQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FreeQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'model': json['model'] == null ? undefined : json['model'],
    };
}

export function FreeQueryRequestToJSON(json: any): FreeQueryRequest {
    return FreeQueryRequestToJSONTyped(json, false);
}

export function FreeQueryRequestToJSONTyped(value?: FreeQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'model': value['model'],
    };
}

