/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type LegacyAiOperationContent
 * 
 * @export
 */
export type LegacyAiOperationContent = Array<{ [key: string]: any; }> | object | string;

export function LegacyAiOperationContentFromJSON(json: any): LegacyAiOperationContent {
    return LegacyAiOperationContentFromJSONTyped(json, false);
}

export function LegacyAiOperationContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyAiOperationContent {
    if (json == null) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function LegacyAiOperationContentToJSON(json: any): any {
    return LegacyAiOperationContentToJSONTyped(json, false);
}

export function LegacyAiOperationContentToJSONTyped(value?: LegacyAiOperationContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

