/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LegacyAiOperationContent } from './LegacyAiOperationContent';
import {
    LegacyAiOperationContentFromJSON,
    LegacyAiOperationContentFromJSONTyped,
    LegacyAiOperationContentToJSON,
    LegacyAiOperationContentToJSONTyped,
} from './LegacyAiOperationContent';

/**
 * 
 * @export
 * @interface LegacyAiOperation
 */
export interface LegacyAiOperation {
    /**
     * 
     * @type {string}
     * @memberof LegacyAiOperation
     */
    action: LegacyAiOperationActionEnum;
    /**
     * Preferred stable node id target for replace/remove operations.
     * @type {string}
     * @memberof LegacyAiOperation
     */
    targetNodeId?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof LegacyAiOperation
     */
    path?: Array<number>;
    /**
     * 
     * @type {LegacyAiOperationContent}
     * @memberof LegacyAiOperation
     */
    content?: LegacyAiOperationContent;
}


/**
 * @export
 */
export const LegacyAiOperationActionEnum = {
    Append: 'append',
    Prepend: 'prepend',
    Replace: 'replace',
    Remove: 'remove',
    Add: 'add'
} as const;
export type LegacyAiOperationActionEnum = typeof LegacyAiOperationActionEnum[keyof typeof LegacyAiOperationActionEnum];


/**
 * Check if a given object implements the LegacyAiOperation interface.
 */
export function instanceOfLegacyAiOperation(value: object): value is LegacyAiOperation {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function LegacyAiOperationFromJSON(json: any): LegacyAiOperation {
    return LegacyAiOperationFromJSONTyped(json, false);
}

export function LegacyAiOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegacyAiOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'targetNodeId': json['targetNodeId'] == null ? undefined : json['targetNodeId'],
        'path': json['path'] == null ? undefined : json['path'],
        'content': json['content'] == null ? undefined : LegacyAiOperationContentFromJSON(json['content']),
    };
}

export function LegacyAiOperationToJSON(json: any): LegacyAiOperation {
    return LegacyAiOperationToJSONTyped(json, false);
}

export function LegacyAiOperationToJSONTyped(value?: LegacyAiOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'targetNodeId': value['targetNodeId'],
        'path': value['path'],
        'content': LegacyAiOperationContentToJSON(value['content']),
    };
}

