/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginEndRequest
 */
export interface LoginEndRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginEndRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginEndRequest
     */
    otp: string;
}

/**
 * Check if a given object implements the LoginEndRequest interface.
 */
export function instanceOfLoginEndRequest(value: object): value is LoginEndRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('otp' in value) || value['otp'] === undefined) return false;
    return true;
}

export function LoginEndRequestFromJSON(json: any): LoginEndRequest {
    return LoginEndRequestFromJSONTyped(json, false);
}

export function LoginEndRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginEndRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'otp': json['otp'],
    };
}

export function LoginEndRequestToJSON(json: any): LoginEndRequest {
    return LoginEndRequestToJSONTyped(json, false);
}

export function LoginEndRequestToJSONTyped(value?: LoginEndRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'otp': value['otp'],
    };
}

