/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginStartRequest
 */
export interface LoginStartRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginStartRequest
     */
    email: string;
}

/**
 * Check if a given object implements the LoginStartRequest interface.
 */
export function instanceOfLoginStartRequest(value: object): value is LoginStartRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function LoginStartRequestFromJSON(json: any): LoginStartRequest {
    return LoginStartRequestFromJSONTyped(json, false);
}

export function LoginStartRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginStartRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function LoginStartRequestToJSON(json: any): LoginStartRequest {
    return LoginStartRequestToJSONTyped(json, false);
}

export function LoginStartRequestToJSONTyped(value?: LoginStartRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

