/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NormalizedExamQuestionPayload
 */
export interface NormalizedExamQuestionPayload {
    /**
     * 
     * @type {string}
     * @memberof NormalizedExamQuestionPayload
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NormalizedExamQuestionPayload
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof NormalizedExamQuestionPayload
     */
    maxPoints: number;
    /**
     * 
     * @type {string}
     * @memberof NormalizedExamQuestionPayload
     */
    rubric: string;
    /**
     * 
     * @type {any}
     * @memberof NormalizedExamQuestionPayload
     */
    spec: any | null;
    /**
     * 
     * @type {any}
     * @memberof NormalizedExamQuestionPayload
     */
    correctAnswer: any | null;
}

/**
 * Check if a given object implements the NormalizedExamQuestionPayload interface.
 */
export function instanceOfNormalizedExamQuestionPayload(value: object): value is NormalizedExamQuestionPayload {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('maxPoints' in value) || value['maxPoints'] === undefined) return false;
    if (!('rubric' in value) || value['rubric'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    if (!('correctAnswer' in value) || value['correctAnswer'] === undefined) return false;
    return true;
}

export function NormalizedExamQuestionPayloadFromJSON(json: any): NormalizedExamQuestionPayload {
    return NormalizedExamQuestionPayloadFromJSONTyped(json, false);
}

export function NormalizedExamQuestionPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): NormalizedExamQuestionPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'maxPoints': json['maxPoints'],
        'rubric': json['rubric'],
        'spec': json['spec'],
        'correctAnswer': json['correctAnswer'],
    };
}

export function NormalizedExamQuestionPayloadToJSON(json: any): NormalizedExamQuestionPayload {
    return NormalizedExamQuestionPayloadToJSONTyped(json, false);
}

export function NormalizedExamQuestionPayloadToJSONTyped(value?: NormalizedExamQuestionPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'maxPoints': value['maxPoints'],
        'rubric': value['rubric'],
        'spec': value['spec'],
        'correctAnswer': value['correctAnswer'],
    };
}

