/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Subject } from './Subject';
import {
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
    SubjectToJSONTyped,
} from './Subject';

/**
 * 
 * @export
 * @interface SubjectsGet200Response
 */
export interface SubjectsGet200Response {
    /**
     * 
     * @type {number}
     * @memberof SubjectsGet200Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof SubjectsGet200Response
     */
    message?: string;
    /**
     * 
     * @type {Array<Subject>}
     * @memberof SubjectsGet200Response
     */
    subjects?: Array<Subject>;
}

/**
 * Check if a given object implements the SubjectsGet200Response interface.
 */
export function instanceOfSubjectsGet200Response(value: object): value is SubjectsGet200Response {
    return true;
}

export function SubjectsGet200ResponseFromJSON(json: any): SubjectsGet200Response {
    return SubjectsGet200ResponseFromJSONTyped(json, false);
}

export function SubjectsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'subjects': json['subjects'] == null ? undefined : ((json['subjects'] as Array<any>).map(SubjectFromJSON)),
    };
}

export function SubjectsGet200ResponseToJSON(json: any): SubjectsGet200Response {
    return SubjectsGet200ResponseToJSONTyped(json, false);
}

export function SubjectsGet200ResponseToJSONTyped(value?: SubjectsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'subjects': value['subjects'] == null ? undefined : ((value['subjects'] as Array<any>).map(SubjectToJSON)),
    };
}

