/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Subject } from './Subject';
import {
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
    SubjectToJSONTyped,
} from './Subject';

/**
 * 
 * @export
 * @interface SubjectsPost201Response
 */
export interface SubjectsPost201Response {
    /**
     * 
     * @type {number}
     * @memberof SubjectsPost201Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof SubjectsPost201Response
     */
    message?: string;
    /**
     * 
     * @type {Subject}
     * @memberof SubjectsPost201Response
     */
    subject?: Subject;
}

/**
 * Check if a given object implements the SubjectsPost201Response interface.
 */
export function instanceOfSubjectsPost201Response(value: object): value is SubjectsPost201Response {
    return true;
}

export function SubjectsPost201ResponseFromJSON(json: any): SubjectsPost201Response {
    return SubjectsPost201ResponseFromJSONTyped(json, false);
}

export function SubjectsPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectsPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'subject': json['subject'] == null ? undefined : SubjectFromJSON(json['subject']),
    };
}

export function SubjectsPost201ResponseToJSON(json: any): SubjectsPost201Response {
    return SubjectsPost201ResponseToJSONTyped(json, false);
}

export function SubjectsPost201ResponseToJSONTyped(value?: SubjectsPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'subject': SubjectToJSON(value['subject']),
    };
}

