/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmissionsIdPutRequestAnswersInner
 */
export interface SubmissionsIdPutRequestAnswersInner {
    /**
     * 
     * @type {number}
     * @memberof SubmissionsIdPutRequestAnswersInner
     */
    questionId?: number;
    /**
     * 
     * @type {any}
     * @memberof SubmissionsIdPutRequestAnswersInner
     */
    answer?: any | null;
}

/**
 * Check if a given object implements the SubmissionsIdPutRequestAnswersInner interface.
 */
export function instanceOfSubmissionsIdPutRequestAnswersInner(value: object): value is SubmissionsIdPutRequestAnswersInner {
    return true;
}

export function SubmissionsIdPutRequestAnswersInnerFromJSON(json: any): SubmissionsIdPutRequestAnswersInner {
    return SubmissionsIdPutRequestAnswersInnerFromJSONTyped(json, false);
}

export function SubmissionsIdPutRequestAnswersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionsIdPutRequestAnswersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['questionId'] == null ? undefined : json['questionId'],
        'answer': json['answer'] == null ? undefined : json['answer'],
    };
}

export function SubmissionsIdPutRequestAnswersInnerToJSON(json: any): SubmissionsIdPutRequestAnswersInner {
    return SubmissionsIdPutRequestAnswersInnerToJSONTyped(json, false);
}

export function SubmissionsIdPutRequestAnswersInnerToJSONTyped(value?: SubmissionsIdPutRequestAnswersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionId': value['questionId'],
        'answer': value['answer'],
    };
}

