/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubmissionsIdPutRequestAnswersInner } from './SubmissionsIdPutRequestAnswersInner';
import {
    SubmissionsIdPutRequestAnswersInnerFromJSON,
    SubmissionsIdPutRequestAnswersInnerFromJSONTyped,
    SubmissionsIdPutRequestAnswersInnerToJSON,
    SubmissionsIdPutRequestAnswersInnerToJSONTyped,
} from './SubmissionsIdPutRequestAnswersInner';
import type { SubmissionsIdPutRequestTeacherScoresInner } from './SubmissionsIdPutRequestTeacherScoresInner';
import {
    SubmissionsIdPutRequestTeacherScoresInnerFromJSON,
    SubmissionsIdPutRequestTeacherScoresInnerFromJSONTyped,
    SubmissionsIdPutRequestTeacherScoresInnerToJSON,
    SubmissionsIdPutRequestTeacherScoresInnerToJSONTyped,
} from './SubmissionsIdPutRequestTeacherScoresInner';

/**
 * 
 * @export
 * @interface SubmissionsIdPutRequest
 */
export interface SubmissionsIdPutRequest {
    /**
     * 
     * @type {Array<SubmissionsIdPutRequestAnswersInner>}
     * @memberof SubmissionsIdPutRequest
     */
    answers?: Array<SubmissionsIdPutRequestAnswersInner>;
    /**
     * 
     * @type {Array<SubmissionsIdPutRequestTeacherScoresInner>}
     * @memberof SubmissionsIdPutRequest
     */
    teacherScores?: Array<SubmissionsIdPutRequestTeacherScoresInner>;
    /**
     * 
     * @type {number}
     * @memberof SubmissionsIdPutRequest
     */
    studentId?: number | null;
}

/**
 * Check if a given object implements the SubmissionsIdPutRequest interface.
 */
export function instanceOfSubmissionsIdPutRequest(value: object): value is SubmissionsIdPutRequest {
    return true;
}

export function SubmissionsIdPutRequestFromJSON(json: any): SubmissionsIdPutRequest {
    return SubmissionsIdPutRequestFromJSONTyped(json, false);
}

export function SubmissionsIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionsIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'answers': json['answers'] == null ? undefined : ((json['answers'] as Array<any>).map(SubmissionsIdPutRequestAnswersInnerFromJSON)),
        'teacherScores': json['teacherScores'] == null ? undefined : ((json['teacherScores'] as Array<any>).map(SubmissionsIdPutRequestTeacherScoresInnerFromJSON)),
        'studentId': json['studentId'] == null ? undefined : json['studentId'],
    };
}

export function SubmissionsIdPutRequestToJSON(json: any): SubmissionsIdPutRequest {
    return SubmissionsIdPutRequestToJSONTyped(json, false);
}

export function SubmissionsIdPutRequestToJSONTyped(value?: SubmissionsIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answers': value['answers'] == null ? undefined : ((value['answers'] as Array<any>).map(SubmissionsIdPutRequestAnswersInnerToJSON)),
        'teacherScores': value['teacherScores'] == null ? undefined : ((value['teacherScores'] as Array<any>).map(SubmissionsIdPutRequestTeacherScoresInnerToJSON)),
        'studentId': value['studentId'],
    };
}

