/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmissionsIdPutRequestTeacherScoresInner
 */
export interface SubmissionsIdPutRequestTeacherScoresInner {
    /**
     * 
     * @type {number}
     * @memberof SubmissionsIdPutRequestTeacherScoresInner
     */
    questionId?: number;
    /**
     * 
     * @type {number}
     * @memberof SubmissionsIdPutRequestTeacherScoresInner
     */
    teacherScore?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SubmissionsIdPutRequestTeacherScoresInner
     */
    teacherFeedback?: string | null;
}

/**
 * Check if a given object implements the SubmissionsIdPutRequestTeacherScoresInner interface.
 */
export function instanceOfSubmissionsIdPutRequestTeacherScoresInner(value: object): value is SubmissionsIdPutRequestTeacherScoresInner {
    return true;
}

export function SubmissionsIdPutRequestTeacherScoresInnerFromJSON(json: any): SubmissionsIdPutRequestTeacherScoresInner {
    return SubmissionsIdPutRequestTeacherScoresInnerFromJSONTyped(json, false);
}

export function SubmissionsIdPutRequestTeacherScoresInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionsIdPutRequestTeacherScoresInner {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['questionId'] == null ? undefined : json['questionId'],
        'teacherScore': json['teacherScore'] == null ? undefined : json['teacherScore'],
        'teacherFeedback': json['teacherFeedback'] == null ? undefined : json['teacherFeedback'],
    };
}

export function SubmissionsIdPutRequestTeacherScoresInnerToJSON(json: any): SubmissionsIdPutRequestTeacherScoresInner {
    return SubmissionsIdPutRequestTeacherScoresInnerToJSONTyped(json, false);
}

export function SubmissionsIdPutRequestTeacherScoresInnerToJSONTyped(value?: SubmissionsIdPutRequestTeacherScoresInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionId': value['questionId'],
        'teacherScore': value['teacherScore'],
        'teacherFeedback': value['teacherFeedback'],
    };
}

