/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDraftRequest
 */
export interface UpdateDraftRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateDraftRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDraftRequest
     */
    format?: UpdateDraftRequestFormatEnum;
    /**
     * 
     * @type {object}
     * @memberof UpdateDraftRequest
     */
    content?: object;
}


/**
 * @export
 */
export const UpdateDraftRequestFormatEnum = {
    SimaVazlat: 'sima_vazlat',
    Oravazlat: 'oravazlat',
    EvesTanterv: 'eves_tanterv',
    Egyeb: 'egyeb'
} as const;
export type UpdateDraftRequestFormatEnum = typeof UpdateDraftRequestFormatEnum[keyof typeof UpdateDraftRequestFormatEnum];


/**
 * Check if a given object implements the UpdateDraftRequest interface.
 */
export function instanceOfUpdateDraftRequest(value: object): value is UpdateDraftRequest {
    return true;
}

export function UpdateDraftRequestFromJSON(json: any): UpdateDraftRequest {
    return UpdateDraftRequestFromJSONTyped(json, false);
}

export function UpdateDraftRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDraftRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'format': json['format'] == null ? undefined : json['format'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function UpdateDraftRequestToJSON(json: any): UpdateDraftRequest {
    return UpdateDraftRequestToJSONTyped(json, false);
}

export function UpdateDraftRequestToJSONTyped(value?: UpdateDraftRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'format': value['format'],
        'content': value['content'],
    };
}

