/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateStudentRequest
 */
export interface UpdateStudentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    email?: string | null;
}

/**
 * Check if a given object implements the UpdateStudentRequest interface.
 */
export function instanceOfUpdateStudentRequest(value: object): value is UpdateStudentRequest {
    return true;
}

export function UpdateStudentRequestFromJSON(json: any): UpdateStudentRequest {
    return UpdateStudentRequestFromJSONTyped(json, false);
}

export function UpdateStudentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStudentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function UpdateStudentRequestToJSON(json: any): UpdateStudentRequest {
    return UpdateStudentRequestToJSONTyped(json, false);
}

export function UpdateStudentRequestToJSONTyped(value?: UpdateStudentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
    };
}

