/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * API documentation for the backend service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorResponse
 */
export interface ValidationErrorResponse {
    /**
     * 
     * @type {number}
     * @memberof ValidationErrorResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ValidationErrorResponse
     */
    reason?: Array<string>;
}

/**
 * Check if a given object implements the ValidationErrorResponse interface.
 */
export function instanceOfValidationErrorResponse(value: object): value is ValidationErrorResponse {
    return true;
}

export function ValidationErrorResponseFromJSON(json: any): ValidationErrorResponse {
    return ValidationErrorResponseFromJSONTyped(json, false);
}

export function ValidationErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function ValidationErrorResponseToJSON(json: any): ValidationErrorResponse {
    return ValidationErrorResponseToJSONTyped(json, false);
}

export function ValidationErrorResponseToJSONTyped(value?: ValidationErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'reason': value['reason'],
    };
}

